// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  VERSION 0.1 — FROZEN SNAPSHOT  (2026-03-31)                           ║
// ║                                                                          ║
// ║  DO NOT EDIT THIS FILE under any circumstances.                          ║
// ║  This is a reference snapshot of the DashboardDetail page as it existed  ║
// ║  at the end of the initial line-chart editing options build.             ║
// ║                                                                          ║
// ║  To make changes, edit src/pages/DashboardDetail.tsx (v0.2).            ║
// ║  Only modify this file if explicitly instructed to do so with a          ║
// ║  specific reference to "v0.1 DashboardDetail" in the request.           ║
// ╚══════════════════════════════════════════════════════════════════════════╝

import { useState, useRef } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  Box,
  Typography,
  IconButton,
  Paper,
  Tooltip,
} from '@mui/material';
import DragIndicatorIcon from '@mui/icons-material/DragIndicator';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import MoreHorizIcon from '@mui/icons-material/MoreHoriz';
import StarBorderIcon from '@mui/icons-material/StarBorder';
import StarIcon from '@mui/icons-material/Star';
import RefreshIcon from '@mui/icons-material/Refresh';
import AddIcon from '@mui/icons-material/Add';
import TuneIcon from '@mui/icons-material/Tune';
import SaveIcon from '@mui/icons-material/Save';
import NavigateNextIcon from '@mui/icons-material/NavigateNext';
import { Button, SegmentedControl } from '@design-system';
import { PageLayout } from '../components/PageLayout';
import { TileType, Tile, TileContent, INITIAL_TILES, ChartVariant } from '../components/TileCharts';
import TileFormModal from '../components/TileFormModal';

// ─── Constants ────────────────────────────────────────────────────────────────

const TIME_RANGES = ['1D', '1W', '1M', '3M', '6M', '1Y', 'Custom'];
const TIME_RANGE_ITEMS = TIME_RANGES.map(r => ({ id: r, text: r }));

// ─── Empty tile placeholder ───────────────────────────────────────────────────

function isLargeTile(type: TileType) {
  return type === 'verticalBar' || type === 'multiBar' || type === 'horizontalBar' || type === 'line';
}

function EmptyTilePlaceholder({ type }: { type: TileType }) {
  const large = isLargeTile(type);
  return (
    <Box sx={{
      border: '1.5px dashed #ccc',
      borderRadius: 2,
      height: 360,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      bgcolor: '#fafafa',
      gridColumn: large ? 'span 2' : 'span 1',
      minWidth: large ? 480 : 280,
      maxWidth: 720,
    }}>
      <Typography variant="body2" color="text.disabled">Tile removed</Typography>
    </Box>
  );
}

// ─── Chart tile ───────────────────────────────────────────────────────────────

interface ChartTileProps {
  tile: Tile;
  isEditMode: boolean;
  isDragOver: boolean;
  onDelete: () => void;
  onDuplicate: () => void;
  onEdit: () => void;
  onDragStart: (e: React.DragEvent) => void;
  onDragOver: (e: React.DragEvent) => void;
  onDrop: (e: React.DragEvent) => void;
  onDragEnd: (e: React.DragEvent) => void;
}

function ChartTile({ tile, isEditMode, isDragOver, onDelete, onDuplicate, onEdit, onDragStart, onDragOver, onDrop, onDragEnd }: ChartTileProps) {
  const large = isLargeTile(tile.type);
  const [hovered, setHovered]     = useState(false);
  const [isDragging, setIsDragging] = useState(false);

  const showActions = isEditMode && hovered && !isDragging;

  const handleDragStart = (e: React.DragEvent) => {
    // Build a rotated clone to use as the drag ghost
    const el = e.currentTarget as HTMLElement;
    const clone = el.cloneNode(true) as HTMLElement;
    clone.style.position   = 'fixed';
    clone.style.top        = '-9999px';
    clone.style.left       = '-9999px';
    clone.style.width      = `${el.offsetWidth}px`;
    clone.style.height     = `${el.offsetHeight}px`;
    clone.style.transform  = 'rotate(4deg)';
    clone.style.opacity    = '0.9';
    clone.style.pointerEvents = 'none';
    document.body.appendChild(clone);
    e.dataTransfer.setDragImage(clone, e.nativeEvent.offsetX, e.nativeEvent.offsetY);
    setTimeout(() => document.body.removeChild(clone), 0);

    setIsDragging(true);
    onDragStart(e);
  };

  const handleDragEnd = (e: React.DragEvent) => {
    setIsDragging(false);
    onDragEnd(e);
  };

  return (
    <Paper
      variant="outlined"
      draggable={isEditMode}
      onDragStart={handleDragStart}
      onDragOver={onDragOver}
      onDrop={onDrop}
      onDragEnd={handleDragEnd}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      sx={{
        borderRadius: 2,
        p: 2,
        cursor: isEditMode ? 'grab' : 'default',
        border: isEditMode
          ? (hovered && !isDragging ? '2px solid' : '1.5px dashed')
          : '1px solid',
        borderColor: isEditMode
          ? (hovered && !isDragging ? 'primary.main' : isDragOver ? 'primary.light' : 'divider')
          : 'divider',
        outline: isDragOver && !hovered ? '2px dashed' : 'none',
        outlineColor: 'primary.light',
        transition: 'border 0.15s ease, border-color 0.15s ease, opacity 0.15s ease',
        bgcolor: isDragOver && !hovered ? 'action.hover' : 'background.paper',
        opacity: isDragging ? 0.4 : 1,
        gridColumn: large ? 'span 2' : 'span 1',
        minWidth: large ? 480 : 280,
        maxWidth: 720,
        height: 360,
        position: 'relative',
        overflow: 'visible',
      }}
    >
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
          {isEditMode && (
            <DragIndicatorIcon sx={{ fontSize: 16, color: 'text.disabled', cursor: 'grab', flexShrink: 0 }} />
          )}
          <Typography variant="subtitle2" fontWeight={600}>{tile.name}</Typography>
        </Box>
        {showActions && (
          <Box sx={{ display: 'flex', gap: 0.5 }}>
            <Tooltip title="Duplicate">
              <IconButton size="small" onClick={e => { e.stopPropagation(); onDuplicate(); }}>
                <ContentCopyIcon sx={{ fontSize: 16 }} />
              </IconButton>
            </Tooltip>
            <Tooltip title="Delete">
              <IconButton size="small" onClick={e => { e.stopPropagation(); onDelete(); }}>
                <DeleteOutlineIcon sx={{ fontSize: 16 }} />
              </IconButton>
            </Tooltip>
            <Tooltip title="Edit">
              <IconButton size="small" onClick={e => { e.stopPropagation(); onEdit(); }}>
                <EditOutlinedIcon sx={{ fontSize: 16 }} />
              </IconButton>
            </Tooltip>
          </Box>
        )}
      </Box>
      <TileContent key={tile.type} type={tile.type} height={280} xAxisInterval={tile.xAxisInterval} splitCount={tile.splitCount} splitSortBy={tile.splitField && tile.splitLimitEnabled && tile.splitLimitMode === 'auto' ? tile.splitAutoParam : undefined} chartVariant={tile.chartVariant} />
    </Paper>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function DashboardDetail() {
  const navigate = useNavigate();
  const { id } = useParams();

  const [isEditMode, setIsEditMode] = useState(false);
  const [tiles, setTiles]           = useState<Tile[]>(INITIAL_TILES);
  const [deletedIds, setDeletedIds] = useState<Set<number>>(new Set());
  const [timeRange, setTimeRange]   = useState('1M');
  const [starred, setStarred]       = useState(false);
  const [hasChanges, setHasChanges] = useState(false);

  // Drag-and-drop
  const dragIdRef   = useRef<number | null>(null);
  const [dragOverId, setDragOverId] = useState<number | null>(null);

  // Modal state
  const [modalOpen, setModalOpen]     = useState(false);
  const [editingTile, setEditingTile] = useState<Tile | undefined>(undefined);

  const dashboardName = id ? decodeURIComponent(id) : 'All Transfers - Last Week';

  // ── Edit mode controls ────────────────────────────────────────────────────

  const enterEdit = () => setIsEditMode(true);

  const cancelEdit = () => {
    setIsEditMode(false);
    setTiles(INITIAL_TILES);
    setDeletedIds(new Set());
    setHasChanges(false);
  };

  const saveEdit = () => {
    setIsEditMode(false);
    setHasChanges(false);
  };

  // ── Drag handlers ─────────────────────────────────────────────────────────

  const handleDragStart = (id: number) => (e: React.DragEvent) => {
    dragIdRef.current = id;
    e.dataTransfer.effectAllowed = 'move';
  };

  const handleDragOver = (id: number) => (e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
    if (id !== dragIdRef.current) setDragOverId(id);
  };

  const handleDrop = (targetId: number) => (e: React.DragEvent) => {
    e.preventDefault();
    const sourceId = dragIdRef.current;
    if (sourceId === null || sourceId === targetId) return;
    setTiles(prev => {
      const next = [...prev];
      const fromIdx = next.findIndex(t => t.id === sourceId);
      const toIdx   = next.findIndex(t => t.id === targetId);
      if (fromIdx === -1 || toIdx === -1) return prev;
      const [removed] = next.splice(fromIdx, 1);
      next.splice(toIdx, 0, removed);
      return next;
    });
    setHasChanges(true);
    setDragOverId(null);
    dragIdRef.current = null;
  };

  const handleDragEnd = () => {
    setDragOverId(null);
    dragIdRef.current = null;
  };

  // ── Tile operations ───────────────────────────────────────────────────────

  const deleteTile = (id: number) => {
    setDeletedIds(prev => new Set(prev).add(id));
    setHasChanges(true);
  };

  const duplicateTile = (id: number) => {
    const tile = tiles.find(t => t.id === id);
    if (!tile) return;
    const newId = Math.max(...tiles.map(t => t.id)) + 1;
    setTiles(prev => [...prev, { ...tile, id: newId }]);
    setHasChanges(true);
  };

  const openNewTileModal = () => {
    setEditingTile(undefined);
    setModalOpen(true);
  };

  const openEditTileModal = (tile: Tile) => {
    setEditingTile(tile);
    setModalOpen(true);
  };

  const handleModalSave = ({ name, type, xAxisField, xAxisInterval, yAxisOperation, yAxisField, splitField, splitLimitEnabled, splitLimit, splitLimitMode, splitAutoParam, splitCount, chartVariant }: { name: string; type: TileType; xAxisField: string; xAxisInterval: string; yAxisOperation: string; yAxisField: string; splitField: string; splitLimitEnabled: boolean; splitLimit: string; splitLimitMode: 'count' | 'auto'; splitAutoParam: string; splitCount: number; splitSortBy: string | undefined; chartVariant: ChartVariant }) => {
    const config = { name, type, xAxisField, xAxisInterval, yAxisOperation, yAxisField, splitField, splitLimitEnabled, splitLimit, splitLimitMode, splitAutoParam, splitCount, chartVariant };
    if (editingTile) {
      setTiles(prev => prev.map(t => t.id === editingTile.id ? { ...t, ...config } : t));
    } else {
      const newId = Math.max(...tiles.map(t => t.id)) + 1;
      setTiles(prev => [...prev, { id: newId, ...config }]);
    }
    setHasChanges(true);
    setModalOpen(false);
  };

  return (
    <PageLayout selectedNavItem="dashboard" contentPadding={0}>
      <Box sx={{ px: 4, pt: 2.5, pb: 4 }}>

        {/* Breadcrumb */}
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, mb: 1.5 }}>
          <Typography
            variant="caption"
            color="text.secondary"
            sx={{ cursor: 'pointer', '&:hover': { color: 'primary.main' } }}
            onClick={() => navigate('/dashboards')}
          >
            Dashboard Home
          </Typography>
          <NavigateNextIcon sx={{ fontSize: 14, color: 'text.disabled' }} />
          <Typography variant="caption" color="text.primary">{dashboardName}</Typography>
        </Box>

        {/* Title row */}
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <Typography variant="h5" fontWeight={700}>{dashboardName}</Typography>
            <IconButton size="small"><MoreHorizIcon fontSize="small" /></IconButton>
            <IconButton size="small" onClick={() => setStarred(v => !v)}>
              {starred
                ? <StarIcon sx={{ fontSize: 18, color: 'secondary.main' }} />
                : <StarBorderIcon sx={{ fontSize: 18 }} />
              }
            </IconButton>
          </Box>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <Typography variant="caption" color="text.secondary">Last refreshed: 10 minutes ago</Typography>
            <IconButton size="small"><RefreshIcon sx={{ fontSize: 18 }} /></IconButton>
          </Box>
        </Box>

        {/* Action bar */}
        <Box sx={{ display: 'flex', alignItems: 'center', mb: isEditMode ? 1.5 : 2.5 }}>
          <Box sx={{ flex: 1 }}>
            <Button variant="outlined" color="secondary" size="small" startIcon={<TuneIcon />}>
              Filters
            </Button>
          </Box>

          <SegmentedControl
            items={TIME_RANGE_ITEMS}
            defaultSelectedId={timeRange}
            size="sm"
            onChange={id => setTimeRange(id as string)}
          />

          <Box sx={{ flex: 1, display: 'flex', justifyContent: 'flex-end' }}>
            {isEditMode ? (
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <Button variant="text" color="secondary" onClick={cancelEdit}>Cancel</Button>
                <Button variant="contained" startIcon={<SaveIcon />} onClick={saveEdit} disabled={!hasChanges}>
                  Save
                </Button>
              </Box>
            ) : (
              <Button variant="outlined" color="secondary" size="small" startIcon={<EditOutlinedIcon />} onClick={enterEdit}>
                Edit
              </Button>
            )}
          </Box>
        </Box>

        {/* New Tile button (edit mode only) */}
        {isEditMode && (
          <Box sx={{ display: 'flex', justifyContent: 'flex-end', mb: 2 }}>
            <Button variant="outlined" color="secondary" startIcon={<AddIcon />} onClick={openNewTileModal}>
              New Tile
            </Button>
          </Box>
        )}

        {/* Tile grid */}
        <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 2 }}>
          {tiles.map(tile =>
            deletedIds.has(tile.id) ? (
              <EmptyTilePlaceholder key={tile.id} type={tile.type} />
            ) : (
              <ChartTile
                key={tile.id}
                tile={tile}
                isEditMode={isEditMode}
                isDragOver={dragOverId === tile.id}
                onDelete={() => deleteTile(tile.id)}
                onDuplicate={() => duplicateTile(tile.id)}
                onEdit={() => openEditTileModal(tile)}
                onDragStart={handleDragStart(tile.id)}
                onDragOver={handleDragOver(tile.id)}
                onDrop={handleDrop(tile.id)}
                onDragEnd={handleDragEnd}
              />
            )
          )}
        </Box>

      </Box>

      {/* Tile form modal */}
      <TileFormModal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        onSave={handleModalSave}
        tile={editingTile}
      />
    </PageLayout>
  );
}
