// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  VERSION 0.1 — FROZEN SNAPSHOT  (2026-03-31)                           ║
// ║                                                                          ║
// ║  DO NOT EDIT THIS FILE under any circumstances.                          ║
// ║  This is a reference snapshot of the TileFormModal including the         ║
// ║  "Display Mode" variant-picker UI for line charts.                       ║
// ║                                                                          ║
// ║  To make changes, edit src/components/TileFormModal.tsx (v0.2).         ║
// ║  Only modify this file if explicitly instructed to do so with a          ║
// ║  specific reference to "v0.1 TileFormModal" in the request.             ║
// ╚══════════════════════════════════════════════════════════════════════════╝

import { useState, useEffect, useRef, forwardRef } from 'react';
import {
  Box,
  Typography,
  TextField,
  Select,
  MenuItem,
  FormControl,
  Divider,
  Paper,
  IconButton,
  Tooltip,
  Dialog,
  DialogTitle,
  DialogContent,
  List,
  ListItemButton,
  ListItemText,
  InputAdornment,
  Checkbox,
  FormControlLabel,
} from '@mui/material';
import RemoveCircleOutlineIcon from '@mui/icons-material/RemoveCircleOutline';
import BarChartIcon from '@mui/icons-material/BarChart';
import AlignHorizontalLeftIcon from '@mui/icons-material/AlignHorizontalLeft';
import ShowChartIcon from '@mui/icons-material/ShowChart';
import DonutSmallIcon from '@mui/icons-material/DonutSmall';
import PieChartIcon from '@mui/icons-material/PieChart';
import TagIcon from '@mui/icons-material/Tag';
import RefreshIcon from '@mui/icons-material/Refresh';
import NavigateNextIcon from '@mui/icons-material/NavigateNext';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import BarChartOutlinedIcon from '@mui/icons-material/BarChartOutlined';
import SearchIcon from '@mui/icons-material/Search';
import { Button, Chips } from '@design-system';
import { TileType, Tile, TileContent, ChartVariant, VARIANT_GROUPS } from './TileCharts';

const AUTO_LIMIT_PARAMS = [
  { value: 'top-avg',    label: 'Top by Average' },
  { value: 'top-max',    label: 'Top by Max Value' },
  { value: 'top-total',  label: 'Top by Total' },
  { value: 'bottom-avg', label: 'Bottom by Average' },
  { value: 'bottom-min', label: 'Bottom by Min Value' },
];

// ─── Tile type options ────────────────────────────────────────────────────────

const TILE_TYPE_OPTIONS = [
  { value: 'verticalBar'   as TileType, label: 'Vert. Bar',  icon: <BarChartIcon /> },
  { value: 'horizontalBar' as TileType, label: 'Hor. Bar',   icon: <AlignHorizontalLeftIcon /> },
  { value: 'line'          as TileType, label: 'Line',        icon: <ShowChartIcon /> },
  { value: 'percent'       as TileType, label: 'Percent',     icon: <DonutSmallIcon /> },
  { value: 'pie'           as TileType, label: 'Pie',         icon: <PieChartIcon /> },
  { value: 'multiBar'      as TileType, label: 'Summary',     icon: <TagIcon /> },
];

const DATASETS = [
  'File Transfers Last Week',
  'All Documents – This Month',
  'Exceptions Overview',
  'Purchase Orders Q1',
  'Supplier Compliance',
];

// ─── Filter data ──────────────────────────────────────────────────────────────

type DataType = 'String' | 'Size' | 'EventSummaryStatus' | 'Direction' | 'Date' | 'BusinessPartner' | 'Boolean';

interface FilterOption {
  label: string;
  dataType: DataType;
  group: string;
}

const GROUP_ORDER = [
  'File Data',
  'Sender Info',
  'Receiver Info',
  'Delivery Details',
  'Event Source',
  'Processing Info',
  'Timestamp',
];

const ALL_FILTERS: FilterOption[] = [
  { label: 'Exceptions',               dataType: 'Boolean',            group: 'File Data' },
  { label: 'Transfer ID',              dataType: 'String',             group: 'File Data' },
  { label: 'Status',                   dataType: 'EventSummaryStatus', group: 'File Data' },
  { label: 'Direction',                dataType: 'Direction',          group: 'File Data' },
  { label: 'Has Exceptions',           dataType: 'Boolean',            group: 'File Data' },
  { label: 'Sender Error Message',     dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender File Name',         dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender Mailbox Path',      dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender Message ID',        dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender Name',              dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender Operation',         dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender Path File Name',    dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender Protocol',          dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender Remote Host',       dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender Remote IP',         dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender User ID',           dataType: 'String',             group: 'Sender Info' },
  { label: 'Sender File Size',         dataType: 'Size',               group: 'Sender Info' },
  { label: 'Sender Status',            dataType: 'EventSummaryStatus', group: 'Sender Info' },
  { label: 'Start (EST)',              dataType: 'Date',               group: 'Sender Info' },
  { label: 'Sender',                   dataType: 'BusinessPartner',    group: 'Sender Info' },
  { label: 'Receiver Error Message',   dataType: 'String',             group: 'Receiver Info' },
  { label: 'Receiver File Name',       dataType: 'String',             group: 'Receiver Info' },
  { label: 'Receiver Mailbox Path',    dataType: 'String',             group: 'Receiver Info' },
  { label: 'Receiver Name',            dataType: 'String',             group: 'Receiver Info' },
  { label: 'Receiver Operation',       dataType: 'String',             group: 'Receiver Info' },
  { label: 'Receiver Path File Name',  dataType: 'String',             group: 'Receiver Info' },
  { label: 'Receiver Protocol',        dataType: 'String',             group: 'Receiver Info' },
  { label: 'Receiver Remote Host',     dataType: 'String',             group: 'Receiver Info' },
  { label: 'Receiver Remote IP',       dataType: 'String',             group: 'Receiver Info' },
  { label: 'Receiver File Size',       dataType: 'Size',               group: 'Receiver Info' },
  { label: 'Receiver Status',          dataType: 'EventSummaryStatus', group: 'Receiver Info' },
  { label: 'End (EST)',                dataType: 'Date',               group: 'Receiver Info' },
  { label: 'Receiver',                 dataType: 'BusinessPartner',    group: 'Receiver Info' },
  { label: 'Delivery Error Message',   dataType: 'String',             group: 'Delivery Details' },
  { label: 'Delivery Status',          dataType: 'EventSummaryStatus', group: 'Delivery Details' },
  { label: 'Delivery Timestamp',       dataType: 'Date',               group: 'Delivery Details' },
  { label: 'Event Source Name',        dataType: 'String',             group: 'Event Source' },
  { label: 'Event Source Type',        dataType: 'String',             group: 'Event Source' },
  { label: 'Event Source URL',         dataType: 'String',             group: 'Event Source' },
  { label: 'Processing Error Message', dataType: 'String',             group: 'Processing Info' },
  { label: 'Processing Status',        dataType: 'EventSummaryStatus', group: 'Processing Info' },
  { label: 'Processing Timestamp',     dataType: 'Date',               group: 'Processing Info' },
  { label: 'Last Run Time',            dataType: 'Date',               group: 'Timestamp' },
  { label: 'Last Event Time',          dataType: 'Date',               group: 'Timestamp' },
  { label: 'Loaded On Timestamp',      dataType: 'Date',               group: 'Timestamp' },
  { label: 'Last Updated on Date',     dataType: 'Date',               group: 'Timestamp' },
];

const TOP_8_FILTER_LABELS = [
  'Status', 'Direction', 'Sender', 'Receiver',
  'Start (EST)', 'End (EST)', 'Has Exceptions', 'Transfer ID',
];
const TOP_8_FILTERS = ALL_FILTERS.filter(f => TOP_8_FILTER_LABELS.includes(f.label));

// ─── Condition options ────────────────────────────────────────────────────────

const CONDITIONS: Record<DataType, string[]> = {
  String:             ['Equal to', 'Not equal to', 'Starts with', 'Does not start with', 'Contains', 'Does not contain', 'Exists', 'Does not exist', 'Including', 'Not including'],
  Size:               ['Greater than', 'Less than', 'Within range'],
  EventSummaryStatus: ['Equals', 'Not Equals', 'Including', 'Not Including'],
  BusinessPartner:    ['Equals', 'Not Equals', 'Including', 'Not Including', 'Starts with (Name)', 'Contains (Name)', 'Starts with (Code/ID)', 'Contains (Code/ID)', 'Exists', 'Does not exist'],
  Date:               ['Today', 'Yesterday', 'This Week', 'Last Week', 'This Month', 'Last Month', 'Custom Range', 'Custom Range + Specific Time'],
  Direction:          ['Equals', 'Not Equals', 'Including', 'Not Including'],
  Boolean:            ['Equals'],
};

const NO_VALUE_CONDITIONS = new Set([
  'Exists', 'Does not exist',
  'Today', 'Yesterday', 'This Week', 'Last Week', 'This Month', 'Last Month',
]);

const VALUE_OPTIONS: Partial<Record<DataType, string[]>> = {
  EventSummaryStatus: ['Success', 'Error', 'Warning', 'Processing', 'Pending'],
  Direction:          ['Inbound', 'Outbound'],
  Boolean:            ['True', 'False'],
};

// ─── Config data ─────────────────────────────────────────────────────────────

const DATE_FILTERS = ALL_FILTERS.filter(f => f.dataType === 'Date').map(f => f.label);
const INTERVALS    = ['Day', 'Week', 'Month', 'Quarter', 'Year'];
const Y_OPERATIONS = ['Count', 'Average', 'Sum'];
const Y_FIELDS     = ['Total', 'File Size', 'Transfer Count', 'Error Count'];
const SPLIT_FIELDS = [
  'Status', 'Direction', 'Sender', 'Receiver',
  'Sender Status', 'Receiver Status', 'Delivery Status', 'Processing Status',
  'Sender Protocol', 'Receiver Protocol', 'Event Source Type',
];

// ─── Config row ───────────────────────────────────────────────────────────────

const ConfigRow = forwardRef<HTMLDivElement, { label: string; value: string; onClick?: () => void }>(
  ({ label, value, onClick }, ref) => (
    <Box ref={ref} onClick={onClick} sx={{
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      px: 1.5, py: 1.25, border: '1px solid', borderColor: 'divider',
      borderRadius: 1, cursor: 'pointer', '&:hover': { bgcolor: 'action.hover' },
    }}>
      <Box>
        <Typography variant="caption" color="text.secondary" display="block" lineHeight={1.2}>{label}</Typography>
        <Typography variant="body2" fontWeight={500}>{value}</Typography>
      </Box>
      <NavigateNextIcon sx={{ fontSize: 18, color: 'text.secondary' }} />
    </Box>
  )
);

// ─── Applied filter type & chip formatter ─────────────────────────────────────

interface AppliedFilter {
  filter: string;
  condition: string;
  value: string;
}

function formatFilterChip(f: AppliedFilter): string {
  const { filter, condition, value } = f;
  switch (condition) {
    case 'Equal to':
    case 'Equals':
      return `${filter} = ${value}`;
    case 'Not equal to':
    case 'Not Equals':
      return `${filter} ≠ ${value}`;
    case 'Starts with':
    case 'Starts with (Name)':
    case 'Starts with (Code/ID)':
      return `${filter} starts: ${value}`;
    case 'Does not start with':
      return `${filter} doesn't start: ${value}`;
    case 'Contains':
    case 'Contains (Name)':
    case 'Contains (Code/ID)':
      return `${filter} contains: ${value}`;
    case 'Does not contain':
      return `${filter} doesn't contain: ${value}`;
    case 'Exists':
      return `${filter} exists`;
    case 'Does not exist':
      return `${filter} missing`;
    case 'Including':
      return `${filter} includes: ${value}`;
    case 'Not Including':
      return `${filter} doesn't include: ${value}`;
    case 'Greater than':
      return `${filter} > ${value}`;
    case 'Less than':
      return `${filter} < ${value}`;
    case 'Within range':
      return `${filter} ${value}`;
    case 'Today':
    case 'Yesterday':
    case 'This Week':
    case 'Last Week':
    case 'This Month':
    case 'Last Month':
      return `${filter}: ${condition}`;
    case 'Custom Range':
    case 'Custom Range + Specific Time':
      return `${filter}: ${value}`;
    default:
      return value ? `${filter} = ${value}` : filter;
  }
}

// ─── Filter row (sidebar) ─────────────────────────────────────────────────────

function FilterRow({ filter, onDelete }: { filter: AppliedFilter; onDelete: () => void }) {
  const chipLabel = formatFilterChip(filter);
  return (
    <Box sx={{
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      px: 1.5, py: 1, border: '1px solid', borderColor: 'divider',
      borderRadius: 1, bgcolor: 'background.paper',
    }}>
      <Box sx={{ flex: 1, minWidth: 0 }}>
        <Typography variant="caption" color="text.secondary" display="block" lineHeight={1.3}>
          {filter.filter}
        </Typography>
        <Chips
          label={chipLabel}
          size="small"
          sx={{ mt: 0.25, height: 20, fontSize: 11, bgcolor: 'grey.100', borderRadius: 1, maxWidth: '100%' }}
        />
      </Box>
      <IconButton size="small" onClick={onDelete} sx={{ ml: 0.5, flexShrink: 0 }}>
        <DeleteOutlineIcon sx={{ fontSize: 16 }} />
      </IconButton>
    </Box>
  );
}

// ─── Props ────────────────────────────────────────────────────────────────────

interface TileFormModalProps {
  open: boolean;
  onClose: () => void;
  onSave: (updates: { name: string; type: TileType; xAxisField: string; xAxisInterval: string; yAxisOperation: string; yAxisField: string; splitField: string; splitLimitEnabled: boolean; splitLimit: string; splitLimitMode: 'count' | 'auto'; splitAutoParam: string; splitCount: number; splitSortBy: string | undefined; chartVariant: ChartVariant }) => void;
  tile?: Tile;
}

// ─── Modal ────────────────────────────────────────────────────────────────────

const POPUP_WIDTH     = 300;
const FLYOUT_WIDTH    = 340;
const POPUP_EST_HEIGHT = 220; // height of the small Apply Filter popup only

export default function TileFormModal({ open, onClose, onSave, tile }: TileFormModalProps) {
  const isEdit = !!tile;

  const [tileName, setTileName]             = useState('');
  const [dataset, setDataset]               = useState('File Transfers Last Week');
  const [tileType, setTileType]             = useState<TileType | null>(null);
  const [appliedFilters, setAppliedFilters] = useState<AppliedFilter[]>([]);

  const [showFilterPopup, setShowFilterPopup]     = useState(false);
  const [showFlyout, setShowFlyout]               = useState(false);
  const [filterSearch, setFilterSearch]           = useState('');
  const [showAll, setShowAll]                     = useState(false);
  const [selectedFilter, setSelectedFilter]       = useState('');
  const [selectedCondition, setSelectedCondition] = useState('');
  const [selectedValue, setSelectedValue]         = useState('');
  const [popupAnchor, setPopupAnchor]             = useState<{ top: number; left: number } | null>(null);

  // X-Axis / Y-Axis / Split Data config
  const [xAxisField, setXAxisField]         = useState('Start (EST)');
  const [xAxisInterval, setXAxisInterval]   = useState('Month');
  const [yAxisOperation, setYAxisOperation] = useState('');
  const [yAxisField, setYAxisField]         = useState('');
  const [splitField, setSplitField]         = useState('');
  const [splitLimitEnabled, setSplitLimitEnabled] = useState(true);
  const [splitLimit, setSplitLimit]         = useState('');
  const [splitLimitMode, setSplitLimitMode] = useState<'count' | 'auto'>('count');
  const [splitAutoParam, setSplitAutoParam] = useState('top-avg');
  const [chartVariant, setChartVariant]     = useState<ChartVariant>('click-highlight');

  // Temp (in-popup) state
  const [configPopup, setConfigPopup]       = useState<'xaxis' | 'yaxis' | 'splitdata' | null>(null);
  const [tempXField, setTempXField]         = useState('');
  const [tempXInterval, setTempXInterval]   = useState('');
  const [tempYOperation, setTempYOperation] = useState('');
  const [tempYField, setTempYField]         = useState('');
  const [tempSplitField, setTempSplitField] = useState('');
  const [tempSplitLimitEnabled, setTempSplitLimitEnabled] = useState(true);
  const [tempSplitLimit, setTempSplitLimit] = useState('');
  const [tempSplitLimitMode, setTempSplitLimitMode] = useState<'count' | 'auto'>('count');
  const [tempSplitAutoParam, setTempSplitAutoParam] = useState('top-avg');
  const [configAnchor, setConfigAnchor]     = useState<{ top: number; left: number } | null>(null);

  const addFilterRef    = useRef<HTMLDivElement>(null);
  const xAxisRowRef     = useRef<HTMLDivElement>(null);
  const yAxisRowRef     = useRef<HTMLDivElement>(null);
  const splitDataRowRef = useRef<HTMLDivElement>(null);
  const dialogPaperRef  = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (open) {
      setTileName(tile?.name ?? '');
      setTileType(tile?.type ?? null);
      setDataset('File Transfers Last Week');
      setAppliedFilters([]);
      setXAxisField(tile?.xAxisField ?? 'Start (EST)');
      setXAxisInterval(tile?.xAxisInterval ?? 'Month');
      setYAxisOperation(tile?.yAxisOperation ?? '');
      setYAxisField(tile?.yAxisField ?? '');
      setSplitField(tile?.splitField ?? '');
      setSplitLimitEnabled(tile?.splitLimitEnabled ?? true);
      setSplitLimit(tile?.splitLimit ?? '');
      setSplitLimitMode(tile?.splitLimitMode ?? 'count');
      setSplitAutoParam(tile?.splitAutoParam ?? 'top-avg');
      setChartVariant(tile?.chartVariant ?? 'click-highlight');
      setConfigPopup(null);
      closeEverything();
    }
  }, [open, tile]);

  const closeEverything = () => {
    setShowFilterPopup(false);
    setShowFlyout(false);
    setFilterSearch('');
    setShowAll(false);
    setSelectedFilter('');
    setSelectedCondition('');
    setSelectedValue('');
  };

  const openConfigPopup = (type: 'xaxis' | 'yaxis' | 'splitdata') => {
    const refMap = { xaxis: xAxisRowRef, yaxis: yAxisRowRef, splitdata: splitDataRowRef };
    const ref = refMap[type];
    if (ref.current) {
      const rect = ref.current.getBoundingClientRect();
      const popupHeight = type === 'splitdata' ? 460 : 300;
      const modalBottom = dialogPaperRef.current
        ? dialogPaperRef.current.getBoundingClientRect().bottom - 16
        : window.innerHeight - 16;
      const top = Math.max(16, Math.min(rect.top, modalBottom - popupHeight));
      setConfigAnchor({ top, left: rect.right + 8 });
    }
    if (type === 'xaxis') {
      setTempXField(xAxisField);
      setTempXInterval(xAxisInterval);
    } else if (type === 'yaxis') {
      setTempYOperation(yAxisOperation);
      setTempYField(yAxisField);
    } else {
      setTempSplitField(splitField);
      setTempSplitLimitEnabled(splitLimitEnabled);
      setTempSplitLimit(splitLimit);
      setTempSplitLimitMode(splitLimitMode);
      setTempSplitAutoParam(splitAutoParam);
    }
    setConfigPopup(type);
  };

  const handleConfigDone = () => {
    if (configPopup === 'xaxis') {
      setXAxisField(tempXField);
      setXAxisInterval(tempXInterval);
    } else if (configPopup === 'yaxis') {
      setYAxisOperation(tempYOperation);
      setYAxisField(tempYField);
    } else if (configPopup === 'splitdata') {
      setSplitField(tempSplitField);
      setSplitLimitEnabled(tempSplitLimitEnabled);
      setSplitLimit(tempSplitLimit);
      setSplitLimitMode(tempSplitLimitMode);
      setSplitAutoParam(tempSplitAutoParam);
    }
    setConfigPopup(null);
  };

  const handleRemoveSplit = () => {
    setSplitField('');
    setSplitLimitEnabled(true);
    setSplitLimit('');
    setSplitLimitMode('count');
    setSplitAutoParam('top-avg');
    setConfigPopup(null);
  };

  const handleOpenFilter = () => {
    if (addFilterRef.current) {
      const rect = addFilterRef.current.getBoundingClientRect();
      const top  = Math.min(rect.top, window.innerHeight - POPUP_EST_HEIGHT - 16);
      setPopupAnchor({ top: Math.max(16, top), left: rect.right + 8 });
    }
    setShowFilterPopup(true);
    setShowFlyout(true);
  };

  const handleApplyFilter = () => {
    if (selectedFilter) {
      setAppliedFilters(prev => [...prev, { filter: selectedFilter, condition: selectedCondition, value: selectedValue }]);
    }
    closeEverything();
  };

  const handleSelectFilter = (label: string) => {
    setSelectedFilter(label);
    setSelectedCondition('');
    setSelectedValue('');
    setShowFlyout(false);
    setFilterSearch('');
  };

  // What to show in the flyout list
  const searchActive = filterSearch.trim().length > 0;
  const listFilters  = searchActive
    ? ALL_FILTERS.filter(f => f.label.toLowerCase().includes(filterSearch.toLowerCase()))
    : showAll ? ALL_FILTERS : TOP_8_FILTERS;

  const useGroups = searchActive || showAll;
  const groupedFilters = GROUP_ORDER.map(g => ({
    group: g,
    filters: listFilters.filter(f => f.group === g),
  })).filter(g => g.filters.length > 0);

  const selectedFilterDef = ALL_FILTERS.find(f => f.label === selectedFilter);
  const conditionOptions  = selectedFilterDef ? CONDITIONS[selectedFilterDef.dataType] : [];
  const valueOptions      = selectedFilterDef ? VALUE_OPTIONS[selectedFilterDef.dataType] : undefined;
  const needsValue        = !!selectedCondition && !NO_VALUE_CONDITIONS.has(selectedCondition);
  const canApply          = !!selectedFilter && !!selectedCondition &&
                            (!needsValue || !!selectedValue);
  const canSave           = tileName.trim() !== '' && tileType !== null;

  const xAxisLabel  = `${xAxisField} by ${xAxisInterval}`;
  const yAxisLabel  = yAxisOperation || 'Choose Axis';
  const splitLabel  = splitField || 'Choose Category';

  // When a split field is set: 16 lines unless the limit checkbox is checked
  const splitCount = splitField
    ? (splitLimitEnabled
        ? (splitLimitMode === 'auto' ? 8 : (splitLimit ? Math.min(16, Math.max(1, parseInt(splitLimit, 10))) : 16))
        : 16)
    : 1;
  const splitSortBy = splitField && splitLimitEnabled && splitLimitMode === 'auto' ? splitAutoParam : undefined;

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="lg"
      fullWidth
      PaperProps={{ ref: dialogPaperRef, sx: { height: '88vh', maxHeight: 820, display: 'flex', flexDirection: 'column', borderRadius: 2 } }}
    >
      <DialogTitle sx={{ pb: 0.5 }}>
        <Typography variant="h6" fontWeight={700} component="span" display="block">{isEdit ? 'Edit Tile' : 'Create New Tile'}</Typography>
        <Typography variant="body2" color="text.secondary">
          Configure your tile settings. Preview updates in real-time.
        </Typography>
      </DialogTitle>
      <Divider />

      <DialogContent sx={{ p: 0, display: 'flex', flex: 1, overflow: 'hidden' }}>

        {/* ── Left panel ──────────────────────────────────────── */}
        <Box sx={{
          width: 340, flexShrink: 0, borderRight: '1px solid', borderColor: 'divider',
          overflowY: 'auto', px: 3, py: 3, display: 'flex', flexDirection: 'column', gap: 3,
        }}>
          <Box>
            <Typography variant="subtitle2" fontWeight={600} sx={{ mb: 1 }}>Tile Name</Typography>
            <TextField placeholder="Name" size="small" fullWidth value={tileName} onChange={e => setTileName(e.target.value)} />
          </Box>

          <Box>
            <Typography variant="subtitle2" fontWeight={600} sx={{ mb: 1 }}>Data</Typography>
            <FormControl fullWidth size="small">
              <Select value={dataset} onChange={e => setDataset(e.target.value)}>
                {DATASETS.map(d => <MenuItem key={d} value={d}>{d}</MenuItem>)}
              </Select>
            </FormControl>
            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 2, mb: 1 }}>Tile Type</Typography>
            <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 1 }}>
              {TILE_TYPE_OPTIONS.map(opt => (
                <Box key={opt.value} onClick={() => setTileType(opt.value)} sx={{
                  display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 0.5,
                  py: 1.5, border: '1px solid',
                  borderColor: tileType === opt.value ? 'primary.main' : 'divider',
                  borderRadius: 1.5, cursor: 'pointer',
                  bgcolor: tileType === opt.value ? 'rgba(43, 122, 140, 0.06)' : 'transparent',
                  transition: 'all 0.15s', '&:hover': { borderColor: 'primary.main', bgcolor: 'action.hover' },
                }}>
                  <Box sx={{ color: tileType === opt.value ? 'primary.main' : 'text.secondary' }}>{opt.icon}</Box>
                  <Typography variant="caption" fontWeight={tileType === opt.value ? 600 : 400}>{opt.label}</Typography>
                </Box>
              ))}
            </Box>
          </Box>

          <Box>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 1 }}>
              <Typography variant="subtitle2" fontWeight={600}>Filters</Typography>
              <Tooltip title="Reset filters">
                <IconButton size="small" onClick={() => setAppliedFilters([])}><RefreshIcon sx={{ fontSize: 16 }} /></IconButton>
              </Tooltip>
            </Box>
            {appliedFilters.length > 0 && (
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.75, mb: 1 }}>
                {appliedFilters.map((f, i) => (
                  <FilterRow key={i} filter={f}
                    onDelete={() => setAppliedFilters(prev => prev.filter((_, j) => j !== i))} />
                ))}
              </Box>
            )}
            <Box ref={addFilterRef} onClick={handleOpenFilter} sx={{
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              px: 1.5, py: 1.25, border: '1px solid', borderColor: 'divider',
              borderRadius: 1, cursor: 'pointer', '&:hover': { bgcolor: 'action.hover' },
            }}>
              <Typography variant="body2" fontWeight={500}>Add Filter</Typography>
              <NavigateNextIcon sx={{ fontSize: 18, color: 'text.secondary' }} />
            </Box>
          </Box>

          <Box>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 1 }}>
              <Typography variant="subtitle2" fontWeight={600}>Configuration</Typography>
              <Tooltip title="Reset configuration">
                <IconButton size="small"><RefreshIcon sx={{ fontSize: 16 }} /></IconButton>
              </Tooltip>
            </Box>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              <ConfigRow ref={xAxisRowRef} label="X-Axis" value={xAxisLabel} onClick={() => openConfigPopup('xaxis')} />
              <ConfigRow ref={yAxisRowRef} label="Y-Axis" value={yAxisLabel} onClick={() => openConfigPopup('yaxis')} />
              <ConfigRow ref={splitDataRowRef} label="Split Data" value={splitLabel} onClick={() => openConfigPopup('splitdata')} />
              <ConfigRow label="Drilldown" value="None" />
            </Box>

            {tileType === 'line' && (
              <Box sx={{ mt: 1 }}>
                <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.75 }}>
                  Display Mode
                </Typography>
                {VARIANT_GROUPS.map((group, gi) => (
                  <Box key={group.label} sx={{ mb: 1 }}>
                    {gi > 0 && <Box sx={{ borderTop: '1px solid', borderColor: 'divider', mb: 1 }} />}
                    <Typography sx={{ fontSize: 9, color: 'text.disabled', textTransform: 'uppercase', letterSpacing: 0.4, mb: 0.5 }}>
                      {group.label}
                    </Typography>
                    <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                      {group.items.map(item => (
                        <Box key={item.value} onClick={() => setChartVariant(item.value)} sx={{
                          px: 1, py: 0.4, borderRadius: 1, cursor: 'pointer',
                          fontSize: 11, userSelect: 'none',
                          bgcolor: chartVariant === item.value ? 'primary.main' : 'transparent',
                          color: chartVariant === item.value ? '#fff' : 'text.secondary',
                          border: '1px solid',
                          borderColor: chartVariant === item.value ? 'primary.main' : 'divider',
                          transition: 'all 0.1s',
                          '&:hover': { borderColor: 'primary.light', color: chartVariant === item.value ? '#fff' : 'primary.main' },
                        }}>
                          {item.label}
                        </Box>
                      ))}
                    </Box>
                  </Box>
                ))}
              </Box>
            )}
          </Box>
        </Box>

        {/* ── Right panel ─────────────────────────────────────── */}
        <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', px: 3, py: 3, gap: 2 }}>
          <Box sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 1.5, px: 2, py: 1.5, flexShrink: 0 }}>
            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 1 }}>Global Filters</Typography>
            <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
              <Chips label="Date = This Week" size="small" variant="rounded" />
              <Chips label="Date = This Week" size="small" variant="rounded" />
            </Box>
          </Box>

          <Box sx={{ height: 360, flexShrink: 0, border: '1px solid', borderColor: 'divider', borderRadius: 1.5, p: 2, display: 'flex', flexDirection: 'column', overflow: 'visible' }}>
            <Typography variant="subtitle2" fontWeight={600} sx={{ mb: appliedFilters.length > 0 ? 0.5 : 1, flexShrink: 0 }}>{tileName || 'Tile Name'}</Typography>
            {appliedFilters.length > 0 && (
              <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5, mb: 1, flexShrink: 0 }}>
                {appliedFilters.map((f, i) => (
                  <Chips key={i} label={formatFilterChip(f)} size="small" variant="rounded" />
                ))}
              </Box>
            )}
            {tileType ? (
              <Box sx={{ flex: 1, minHeight: 0, overflow: 'visible' }}><TileContent type={tileType} height={280} xAxisInterval={xAxisInterval} splitCount={splitCount} splitSortBy={splitSortBy} chartVariant={chartVariant} /></Box>
            ) : (
              <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 1.5, border: '1px solid', borderColor: 'divider', borderRadius: 1.5 }}>
                <Box sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 1.5, p: 1.5 }}>
                  <BarChartOutlinedIcon sx={{ fontSize: 28, color: 'text.secondary' }} />
                </Box>
                <Typography variant="h6" fontWeight={600}>Select Data &amp; Type</Typography>
                <Typography variant="body2" color="text.secondary">No data to display, select data to create a chart.</Typography>
              </Box>
            )}
          </Box>

          <Box sx={{ display: 'flex', justifyContent: 'flex-end', gap: 1, flexShrink: 0 }}>
            <Button variant="text" color="secondary" onClick={onClose}>Cancel</Button>
            <Button variant="contained" disabled={!canSave} onClick={() => { if (canSave) onSave({ name: tileName.trim(), type: tileType!, xAxisField, xAxisInterval, yAxisOperation, yAxisField, splitField, splitLimitEnabled, splitLimit, splitLimitMode, splitAutoParam, splitCount, splitSortBy, chartVariant }); }}>Save</Button>
          </Box>
        </Box>
      </DialogContent>

      {/* ── Config popup overlay ────────────────────────────────────────── */}
      {configPopup && (
        <Box sx={{ position: 'fixed', inset: 0, zIndex: 1400 }} onClick={() => setConfigPopup(null)}>
          <Paper
            elevation={8}
            onClick={e => e.stopPropagation()}
            sx={{
              position: 'fixed',
              top: configAnchor?.top ?? 300,
              left: configAnchor?.left ?? 360,
              width: configPopup === 'splitdata' ? 280 : 240,
              borderRadius: 2,
              border: '1px solid',
              borderColor: 'divider',
              p: 2,
              display: 'flex',
              flexDirection: 'column',
              gap: 1.5,
            }}
          >
            <Typography variant="subtitle2" fontWeight={600}>
              {configPopup === 'xaxis' ? 'X-Axis' : configPopup === 'yaxis' ? 'Y-Axis' : 'Split Data into Multiple Lines'}
            </Typography>

            {configPopup === 'xaxis' && (
              <>
                <Box>
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.5 }}>Field</Typography>
                  <FormControl fullWidth size="small">
                    <Select value={tempXField} onChange={e => setTempXField(e.target.value)}>
                      {DATE_FILTERS.map(f => <MenuItem key={f} value={f}>{f}</MenuItem>)}
                    </Select>
                  </FormControl>
                </Box>
                <Box>
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.5 }}>Interval</Typography>
                  <FormControl fullWidth size="small">
                    <Select value={tempXInterval} onChange={e => setTempXInterval(e.target.value)}>
                      {INTERVALS.map(i => <MenuItem key={i} value={i}>{i}</MenuItem>)}
                    </Select>
                  </FormControl>
                </Box>
              </>
            )}

            {configPopup === 'yaxis' && (
              <>
                <Box>
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.5 }}>Operation</Typography>
                  <FormControl fullWidth size="small">
                    <Select
                      value={tempYOperation}
                      onChange={e => { setTempYOperation(e.target.value); setTempYField(''); }}
                      displayEmpty
                      renderValue={v => v || 'Select'}
                    >
                      {Y_OPERATIONS.map(op => <MenuItem key={op} value={op}>{op}</MenuItem>)}
                    </Select>
                  </FormControl>
                </Box>
                <Box>
                  <Typography
                    variant="caption"
                    color={tempYOperation === 'Sum' || tempYOperation === 'Average' ? 'text.secondary' : 'text.disabled'}
                    sx={{ display: 'block', mb: 0.5 }}
                  >
                    Field
                  </Typography>
                  <FormControl fullWidth size="small" disabled={tempYOperation !== 'Sum' && tempYOperation !== 'Average'}>
                    <Select
                      value={tempYField}
                      onChange={e => setTempYField(e.target.value)}
                      displayEmpty
                      renderValue={v => v || 'Total'}
                    >
                      {Y_FIELDS.map(f => <MenuItem key={f} value={f}>{f}</MenuItem>)}
                    </Select>
                  </FormControl>
                  {tempYOperation !== 'Sum' && tempYOperation !== 'Average' && (
                    <Typography variant="caption" color="text.disabled" sx={{ display: 'block', mt: 0.5 }}>
                      Choose a "sum" or "average" operation to enable this field.
                    </Typography>
                  )}
                </Box>
              </>
            )}

            {configPopup === 'splitdata' && (
              <>
                <Box>
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.5 }}>Field</Typography>
                  <FormControl fullWidth size="small">
                    <Select
                      value={tempSplitField}
                      onChange={e => setTempSplitField(e.target.value)}
                      displayEmpty
                      renderValue={v => v || 'Select Field'}
                    >
                      {SPLIT_FIELDS.map(f => <MenuItem key={f} value={f}>{f}</MenuItem>)}
                    </Select>
                  </FormControl>
                </Box>
                <FormControlLabel
                  control={
                    <Checkbox
                      size="small"
                      checked={tempSplitLimitEnabled}
                      onChange={e => setTempSplitLimitEnabled(e.target.checked)}
                    />
                  }
                  label={<Typography variant="body2">Limit number of Splits</Typography>}
                  sx={{ mx: 0, my: -0.5 }}
                />
                {tempSplitLimitEnabled && (
                  <>
                    <Box sx={{ display: 'flex', gap: 0.5 }}>
                      {(['count', 'auto'] as const).map(mode => (
                        <Box
                          key={mode}
                          onClick={() => setTempSplitLimitMode(mode)}
                          sx={{
                            flex: 1, py: 0.75, textAlign: 'center', borderRadius: 1, cursor: 'pointer',
                            border: '1px solid', fontSize: 12, fontFamily: 'Geist, sans-serif',
                            borderColor: tempSplitLimitMode === mode ? 'primary.main' : 'divider',
                            bgcolor: tempSplitLimitMode === mode ? 'primary.50' : 'transparent',
                            color: tempSplitLimitMode === mode ? 'primary.main' : 'text.secondary',
                            fontWeight: tempSplitLimitMode === mode ? 600 : 400,
                            '&:hover': { bgcolor: 'action.hover' },
                          }}
                        >
                          {mode === 'count' ? 'Manual' : 'Auto (8)'}
                        </Box>
                      ))}
                    </Box>
                    {tempSplitLimitMode === 'count' ? (
                      <Box>
                        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.5 }}>Number of Items</Typography>
                        <TextField
                          size="small"
                          fullWidth
                          type="number"
                          value={tempSplitLimit}
                          onChange={e => setTempSplitLimit(e.target.value)}
                          inputProps={{ min: 1 }}
                        />
                      </Box>
                    ) : (
                      <Box>
                        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.5 }}>Select top 8 by</Typography>
                        <FormControl fullWidth size="small">
                          <Select
                            value={tempSplitAutoParam}
                            onChange={e => setTempSplitAutoParam(e.target.value)}
                          >
                            {AUTO_LIMIT_PARAMS.map(p => (
                              <MenuItem key={p.value} value={p.value}>{p.label}</MenuItem>
                            ))}
                          </Select>
                        </FormControl>
                      </Box>
                    )}
                  </>
                )}
                <Box
                  onClick={handleRemoveSplit}
                  sx={{
                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 0.75,
                    py: 1, border: '1px solid', borderColor: 'divider', borderRadius: 1,
                    cursor: 'pointer', '&:hover': { bgcolor: 'action.hover' },
                  }}
                >
                  <RemoveCircleOutlineIcon sx={{ fontSize: 18, color: 'text.secondary' }} />
                  <Typography variant="body2" color="text.secondary">Remove Split</Typography>
                </Box>
              </>
            )}

            <Divider sx={{ mx: -2 }} />
            <Box sx={{ display: 'flex', justifyContent: 'flex-end', gap: 1 }}>
              <Button variant="text" color="secondary" onClick={() => setConfigPopup(null)}>Cancel</Button>
              <Button
                variant="contained"
                onClick={handleConfigDone}
                disabled={
                  configPopup === 'xaxis' ? !tempXField :
                  configPopup === 'yaxis' ? !tempYOperation :
                  !tempSplitField
                }
              >
                Done
              </Button>
            </Box>
          </Paper>
        </Box>
      )}

      {/* ── Filter overlay ──────────────────────────────────────────────── */}
      {showFilterPopup && (
        <Box sx={{ position: 'fixed', inset: 0, zIndex: 1400 }} onClick={closeEverything}>

          {/* Apply Filter popup */}
          <Paper
            elevation={8}
            onClick={e => e.stopPropagation()}
            sx={{
              position: 'fixed',
              top: popupAnchor?.top ?? 200,
              left: popupAnchor?.left ?? 400,
              width: POPUP_WIDTH,
              borderRadius: 2,
              border: '1px solid',
              borderColor: 'divider',
              p: 2,
              display: 'flex',
              flexDirection: 'column',
              gap: 1.5,
            }}
          >
            <Typography variant="subtitle2" fontWeight={600}>Apply Filter</Typography>

            {/* Filter select — clicking opens the flyout */}
            <FormControl fullWidth size="small">
              <Select
                value={selectedFilter}
                open={false}
                onOpen={() => setShowFlyout(v => !v)}
                displayEmpty
                renderValue={v => v || 'Select a filter'}
              >
                <MenuItem value="" />
              </Select>
            </FormControl>

            {/* Condition */}
            <FormControl fullWidth size="small" disabled={!selectedFilter}>
              <Select
                value={selectedCondition}
                onChange={e => { setSelectedCondition(e.target.value); setSelectedValue(''); }}
                displayEmpty
                renderValue={v => v || 'Condition'}
              >
                {conditionOptions.map(c => <MenuItem key={c} value={c}>{c}</MenuItem>)}
              </Select>
            </FormControl>

            {/* Value */}
            {needsValue && (
              valueOptions ? (
                <FormControl fullWidth size="small">
                  <Select value={selectedValue} onChange={e => setSelectedValue(e.target.value)} displayEmpty renderValue={v => v || 'Select value'}>
                    {valueOptions.map(v => <MenuItem key={v} value={v}>{v}</MenuItem>)}
                  </Select>
                </FormControl>
              ) : (
                <TextField
                  placeholder="Value"
                  size="small"
                  fullWidth
                  value={selectedValue}
                  onChange={e => setSelectedValue(e.target.value)}
                  type={selectedFilterDef?.dataType === 'Size' ? 'number' : 'text'}
                />
              )
            )}

            <Divider sx={{ mx: -2 }} />

            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <IconButton size="small" onClick={closeEverything}>
                <DeleteOutlineIcon sx={{ fontSize: 18 }} />
              </IconButton>
              <Box sx={{ display: 'flex', gap: 1 }}>
                <Button variant="text" color="secondary" onClick={closeEverything}>Cancel</Button>
                <Button variant="contained" onClick={handleApplyFilter} disabled={!canApply}>Done</Button>
              </Box>
            </Box>
          </Paper>

          {/* Filter flyout */}
          {showFlyout && (
            <Paper
              elevation={8}
              onClick={e => e.stopPropagation()}
              sx={{
                position: 'fixed',
                top: Math.max(16, Math.min(popupAnchor?.top ?? 200, window.innerHeight - (showAll ? 800 : 640) - 16)),
                left: (popupAnchor?.left ?? 400) + POPUP_WIDTH + 8,
                width: FLYOUT_WIDTH,
                borderRadius: 2,
                border: '1px solid',
                borderColor: 'divider',
                overflow: 'hidden',
                display: 'flex',
                flexDirection: 'column',
                maxHeight: showAll ? 800 : 640,
              }}
            >
              {/* Search */}
              <Box sx={{ px: 2, pt: 1.5, pb: 1, flexShrink: 0 }}>
                <TextField
                  placeholder="Filters"
                  size="small"
                  fullWidth
                  autoFocus
                  value={filterSearch}
                  onChange={e => setFilterSearch(e.target.value)}
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <SearchIcon sx={{ fontSize: 18, color: 'text.disabled' }} />
                      </InputAdornment>
                    ),
                  }}
                />
              </Box>
              <Divider />

              {/* List */}
              <List dense disablePadding sx={{ flex: 1, overflowY: 'auto' }}>
                {useGroups ? (
                  groupedFilters.length > 0 ? groupedFilters.map(({ group, filters }) => (
                    <Box key={group}>
                      <Box sx={{ px: 2, py: 0.5, bgcolor: 'grey.50', position: 'sticky', top: 0, zIndex: 1 }}>
                        <Typography variant="caption" color="text.secondary" fontWeight={600}>{group}</Typography>
                      </Box>
                      {filters.map(f => (
                        <ListItemButton key={f.label} selected={selectedFilter === f.label} onClick={() => handleSelectFilter(f.label)} sx={{ px: 2, py: 1 }}>
                          <ListItemText primary={f.label} primaryTypographyProps={{ variant: 'body2' }} />
                        </ListItemButton>
                      ))}
                    </Box>
                  )) : (
                    <Box sx={{ px: 2, py: 2, textAlign: 'center' }}>
                      <Typography variant="body2" color="text.secondary">No filters match your search</Typography>
                    </Box>
                  )
                ) : (
                  listFilters.map(f => (
                    <ListItemButton key={f.label} selected={selectedFilter === f.label} onClick={() => handleSelectFilter(f.label)} sx={{ px: 2, py: 1 }}>
                      <ListItemText primary={f.label} primaryTypographyProps={{ variant: 'body2' }} />
                    </ListItemButton>
                  ))
                )}
              </List>

              {/* Show all / Show less button */}
              {!searchActive && (
                <>
                  <Divider />
                  <Box
                    onClick={() => setShowAll(v => !v)}
                    sx={{
                      mx: 1.5, my: 1.5, py: 1.25,
                      border: '1px solid', borderColor: 'divider', borderRadius: 1.5,
                      textAlign: 'center', cursor: 'pointer',
                      '&:hover': { bgcolor: 'action.hover' },
                    }}
                  >
                    <Typography variant="body2" color="text.secondary">
                      {showAll ? 'Show less' : 'Show all filters'}
                    </Typography>
                  </Box>
                </>
              )}
            </Paper>
          )}
        </Box>
      )}
    </Dialog>
  );
}
