// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  VERSION 0.1 — FROZEN SNAPSHOT  (2026-03-31)                           ║
// ║                                                                          ║
// ║  DO NOT EDIT THIS FILE under any circumstances.                          ║
// ║  This is a reference snapshot of the line-chart editing options          ║
// ║  (ChartVariant, VARIANT_GROUPS, MultiLineChart) as they existed at       ║
// ║  the end of the initial build.                                           ║
// ║                                                                          ║
// ║  To make changes, edit src/components/TileCharts.tsx (v0.2).            ║
// ║  Only modify this file if explicitly instructed to do so with a          ║
// ║  specific reference to "v0.1 TileCharts" in the request.                ║
// ╚══════════════════════════════════════════════════════════════════════════╝

import { useState, useEffect, useRef } from 'react';
import { Box, Typography, Menu, MenuItem, ListItemIcon, ListItemText } from '@mui/material';
import CheckIcon from '@mui/icons-material/Check';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';
import {
  BarChart, Bar,
  LineChart, Line,
  AreaChart, Area,
  PieChart, Pie, Cell,
  XAxis, YAxis,
  CartesianGrid,
  Tooltip as RechartsTooltip,
  Legend,
  ResponsiveContainer,
  Brush,
} from 'recharts';

// ─── Types ────────────────────────────────────────────────────────────────────

export type TileType = 'verticalBar' | 'multiBar' | 'horizontalBar' | 'line' | 'percent' | 'pie';

export type ChartVariant =
  | 'click-highlight'
  | 'hover-isolate'
  | 'always-dim'
  | 'selected-only'
  | 'small-multiples'
  | 'focus-context'
  | 'log-scale'
  | 'normalized'
  | 'inline-labels'
  | 'floating-labels';

export const VARIANT_GROUPS: { label: string; items: { value: ChartVariant; label: string }[] }[] = [
  { label: 'Interaction', items: [
    { value: 'click-highlight', label: 'Click' },
    { value: 'hover-isolate',   label: 'Hover' },
    { value: 'always-dim',      label: 'Top 5' },
    { value: 'selected-only',   label: 'Selected' },
  ]},
  { label: 'Layout', items: [
    { value: 'small-multiples', label: 'Multiples' },
    { value: 'focus-context',   label: 'Zoom' },
  ]},
  { label: 'Scale', items: [
    { value: 'log-scale',  label: 'Log' },
    { value: 'normalized', label: '100%' },
  ]},
  { label: 'Labels', items: [
    { value: 'inline-labels',   label: 'Inline' },
    { value: 'floating-labels', label: 'Floating' },
  ]},
];

export interface Tile {
  id: number;
  name: string;
  type: TileType;
  xAxisField?: string;
  xAxisInterval?: string;
  yAxisOperation?: string;
  yAxisField?: string;
  splitField?: string;
  splitLimitEnabled?: boolean;
  splitLimit?: string;
  splitLimitMode?: 'count' | 'auto';
  splitAutoParam?: string;
  splitCount?: number;
  chartVariant?: ChartVariant;
}

// ─── Colors ──────────────────────────────────────────────────────────────────

export const CHART_COLORS = [
  '#5a85a1', // 1
  '#00A6C8', // 2
  '#00BFA0', // 3
  '#4CB81B', // 4
  '#8DBE1B', // 5
  '#C9B800', // 6
  '#CC7A18', // 7
  '#D43012', // 8
  '#C0238A', // 9
  '#1B81C5', // 10
  '#00A49E', // 11
  '#00C660', // 12
  '#7B5EA7', // 13
  '#E05C8A', // 14
  '#6B8E23', // 15
  '#B8860B', // 16
  '#E0E0E0', // Other
];

export const PRIMARY = CHART_COLORS[0];
const SERIES = [CHART_COLORS[0], CHART_COLORS[1], CHART_COLORS[2], CHART_COLORS[3]];

// ─── Mock data ────────────────────────────────────────────────────────────────

const BAR_DATA = [
  { date: 'Jan 1',  value: 3800000 },
  { date: 'Jan 5',  value: 9200000 },
  { date: 'Jan 9',  value: 7100000 },
  { date: 'Jan 13', value: 41000000 },
  { date: 'Jan 17', value: 15000000 },
  { date: 'Jan 21', value: 6500000 },
  { date: 'Jan 25', value: 30000000 },
  { date: 'Jan 29', value: 12000000 },
];

const MULTI_BAR_DATA = [
  { date: 'Jan 1',  a: 4000000,  b: 7000000,  c: 9000000,  d: 5000000 },
  { date: 'Jan 5',  a: 18000000, b: 20000000, c: 15000000, d: 10000000 },
  { date: 'Jan 9',  a: 12000000, b: 8000000,  c: 22000000, d: 16000000 },
  { date: 'Jan 13', a: 25000000, b: 30000000, c: 18000000, d: 12000000 },
  { date: 'Jan 17', a: 10000000, b: 14000000, c: 20000000, d: 8000000 },
  { date: 'Jan 21', a: 22000000, b: 16000000, c: 12000000, d: 18000000 },
  { date: 'Jan 25', a: 28000000, b: 22000000, c: 10000000, d: 14000000 },
  { date: 'Jan 29', a: 16000000, b: 18000000, c: 15000000, d: 20000000 },
];

export const SPLIT_SERIES_KEYS = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p'] as const;
export type SplitSeriesKey = typeof SPLIT_SERIES_KEYS[number];

export const SERIES_NAMES: Record<SplitSeriesKey, string> = {
  a: 'Acme Corporation',
  b: 'Global Logistics Inc.',
  c: 'Pacific Rim Trading Co.',
  d: 'Sunrise Healthcare Systems',
  e: 'Metro Distribution Partners',
  f: 'Allied Manufacturing Group',
  g: 'Coastal Supply Chain LLC',
  h: 'Summit Retail Solutions',
  i: 'Horizon Technology Partners',
  j: 'Blue Ridge Freight & Logistics',
  k: 'Cascade Systems International',
  l: 'Pinnacle Wholesale Distributors',
  m: 'Northern Tier Fulfillment',        // thousands range
  n: 'Vertex Micro Components Ltd.',     // hundreds range
  o: 'Relic Legacy Systems Co.',         // near-zero (occasional activity)
  p: 'Dormant Ventures LLC',             // all zeros
};

type LineRow = { date: string } & Record<SplitSeriesKey, number>;

const M = 1e6;

// ─── Line data generator (always last 2 years, granularity set by interval) ───

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

type SeriesCfg =
  | { kind: 'millions'; base: number; trend: number; s1: number; s2: number }
  | { kind: 'thousands'; base: number; trend: number; s1: number; s2: number }
  | { kind: 'hundreds';  base: number; trend: number; s1: number; s2: number }
  | { kind: 'sparse' }
  | { kind: 'zero' };

// Per-series shape
const SERIES_CONFIGS: SeriesCfg[] = [
  { kind: 'millions',  base: 55, trend:  0.30, s1: 1.2, s2: 0.7 },  // a
  { kind: 'millions',  base: 22, trend:  0.65, s1: 2.4, s2: 1.3 },  // b
  { kind: 'millions',  base: 18, trend:  1.20, s1: 3.7, s2: 2.1 },  // c
  { kind: 'millions',  base:  5, trend:  0.25, s1: 5.1, s2: 3.4 },  // d
  { kind: 'millions',  base: 35, trend:  0.08, s1: 0.8, s2: 4.2 },  // e
  { kind: 'millions',  base: 18, trend:  0.55, s1: 4.3, s2: 0.9 },  // f
  { kind: 'millions',  base: 45, trend:  0.05, s1: 1.9, s2: 2.8 },  // g (flat)
  { kind: 'millions',  base: 10, trend:  0.70, s1: 3.1, s2: 5.0 },  // h
  { kind: 'millions',  base: 65, trend: -0.20, s1: 2.6, s2: 1.7 },  // i (declining)
  { kind: 'millions',  base:  8, trend:  0.50, s1: 6.2, s2: 3.9 },  // j
  { kind: 'millions',  base: 38, trend:  0.15, s1: 0.5, s2: 2.3 },  // k
  { kind: 'millions',  base: 28, trend: -0.40, s1: 4.8, s2: 1.1 },  // l (declining)
  { kind: 'thousands', base: 8.4, trend: 0.45, s1: 2.9, s2: 1.6 }, // m ~8,400 → ~12,000
  { kind: 'hundreds',  base: 3.2, trend: 0.20, s1: 4.1, s2: 3.3 }, // n ~320 → ~380
  { kind: 'sparse' },                                                 // o near-zero, occasional spikes
  { kind: 'zero' },                                                   // p all zeros
];

function buildSeriesValue(cfg: SeriesCfg, i: number, total: number): number {
  if (cfg.kind === 'zero') return 0;
  if (cfg.kind === 'sparse') {
    // A handful of small non-zero values scattered across the range
    const spike = Math.sin(i * 0.8 + 1.1) > 0.85;
    return spike ? Math.round(10 + Math.abs(Math.sin(i * 2.3)) * 40) : 0;
  }
  const t = total > 1 ? i / (total - 1) : 0;
  const noise = Math.sin(i * 1.3 + cfg.s1) * 0.12 + Math.sin(i * 0.5 + cfg.s2) * 0.07;
  const raw = cfg.base * (1 + cfg.trend * t + noise);
  if (cfg.kind === 'millions')  return Math.max(M,      Math.round(raw * M));
  if (cfg.kind === 'thousands') return Math.max(100,    Math.round(raw * 1000));
  if (cfg.kind === 'hundreds')  return Math.max(10,     Math.round(raw * 100));
  return 0;
}

function generateLineData(interval: string): LineRow[] {
  // Range: exactly 2 years back from Mar 30 2026
  const END   = new Date(2026, 2, 30);
  const START = new Date(2024, 2, 30);

  const dates: Date[] = [];

  if (interval === 'Day') {
    for (let d = new Date(START); d <= END; d.setDate(d.getDate() + 1))
      dates.push(new Date(d));
  } else if (interval === 'Week') {
    for (let d = new Date(START); d <= END; d.setDate(d.getDate() + 7))
      dates.push(new Date(d));
  } else if (interval === 'Month') {
    for (let d = new Date(START.getFullYear(), START.getMonth(), 1); d <= END; d.setMonth(d.getMonth() + 1))
      dates.push(new Date(d));
  } else if (interval === 'Quarter') {
    const qStart = new Date(START.getFullYear(), Math.floor(START.getMonth() / 3) * 3, 1);
    for (let d = new Date(qStart); d <= END; d.setMonth(d.getMonth() + 3))
      dates.push(new Date(d));
  } else {
    for (let y = START.getFullYear(); y <= END.getFullYear(); y++)
      dates.push(new Date(y, 0, 1));
  }

  const total = dates.length;

  return dates.map((d, i) => {
    let label: string;
    if (interval === 'Month') {
      label = `${MONTHS[d.getMonth()]} '${String(d.getFullYear()).slice(2)}`;
    } else if (interval === 'Quarter') {
      label = `Q${Math.floor(d.getMonth() / 3) + 1} '${String(d.getFullYear()).slice(2)}`;
    } else if (interval === 'Year') {
      label = String(d.getFullYear());
    } else {
      label = `${MONTHS[d.getMonth()]} ${d.getDate()}`;
    }
    const row = { date: label } as LineRow;
    SPLIT_SERIES_KEYS.forEach((key, si) => {
      row[key] = buildSeriesValue(SERIES_CONFIGS[si], i, total);
    });
    return row;
  });
}

const LINE_DATA: Record<string, LineRow[]> = {
  Day:     generateLineData('Day'),
  Week:    generateLineData('Week'),
  Month:   generateLineData('Month'),
  Quarter: generateLineData('Quarter'),
  Year:    generateLineData('Year'),
};

const H_BAR_DATA = [
  { name: 'Category na...', value: 135666 },
  { name: 'Category na...', value: 72000 },
  { name: 'Category na...', value: 70000 },
  { name: 'Category na...', value: 68000 },
  { name: 'Category na...', value: 12000 },
];

const PIE_DATA = [
  { name: 'Label', value: 35, color: CHART_COLORS[0] },
  { name: 'Label', value: 25, color: CHART_COLORS[1] },
  { name: 'Label', value: 30, color: CHART_COLORS[2] },
  { name: 'Label', value: 10, color: CHART_COLORS[12] },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function fmtY(v: number) {
  if (v === 0) return '0';
  if (v >= 1e9) return `${(v / 1e9).toFixed(1)}B`;
  if (v >= 1e6) return `${v / 1e6}M`;
  if (v >= 1e3) return `${(v / 1e3).toFixed(1)}K`;
  return String(v);
}

const GEIST = 'Geist, sans-serif';
const TICK = { fontSize: 10, fill: '#888', fontFamily: GEIST };
const TOOLTIP_STYLE = { borderRadius: 8, boxShadow: '0 4px 12px rgba(0,0,0,0.15)', fontFamily: GEIST };
const TOOLTIP_LABEL_STYLE = { fontFamily: GEIST };
const TOOLTIP_ITEM_STYLE = { fontFamily: GEIST };
const GRID = { vertical: false, strokeDasharray: '3 3', stroke: '#e0e0e0' } as const;

// ─── Chart components ─────────────────────────────────────────────────────────

function VertBarChart({ height }: { height: number }) {
  return (
    <ResponsiveContainer width="100%" height={height}>
      <BarChart data={BAR_DATA} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}>
        <CartesianGrid {...GRID} />
        <XAxis dataKey="date" tick={TICK} axisLine={false} tickLine={false} />
        <YAxis tickFormatter={fmtY} tick={TICK} axisLine={false} tickLine={false} width={36}
          label={{ value: 'Y vertical label', angle: -90, position: 'insideLeft', offset: 10, style: { fontSize: 10, fill: '#aaa', fontFamily: GEIST } }} />
        <RechartsTooltip formatter={(v: any) => fmtY(v as number)} contentStyle={TOOLTIP_STYLE} labelStyle={TOOLTIP_LABEL_STYLE} itemStyle={TOOLTIP_ITEM_STYLE} />
        <Bar dataKey="value" fill={PRIMARY} radius={[2, 2, 0, 0]} />
      </BarChart>
    </ResponsiveContainer>
  );
}

function MultiBarChart({ height }: { height: number }) {
  return (
    <ResponsiveContainer width="100%" height={height}>
      <BarChart data={MULTI_BAR_DATA} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}>
        <CartesianGrid {...GRID} />
        <XAxis dataKey="date" tick={TICK} axisLine={false} tickLine={false} />
        <YAxis tickFormatter={fmtY} tick={TICK} axisLine={false} tickLine={false} width={36}
          label={{ value: 'Y vertical label', angle: -90, position: 'insideLeft', offset: 10, style: { fontSize: 10, fill: '#aaa', fontFamily: GEIST } }} />
        <RechartsTooltip formatter={(v: any) => fmtY(v as number)} contentStyle={TOOLTIP_STYLE} labelStyle={TOOLTIP_LABEL_STYLE} itemStyle={TOOLTIP_ITEM_STYLE} />
        <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: 11, fontFamily: GEIST }} formatter={() => 'Label'} />
        <Bar dataKey="a" fill={SERIES[0]} radius={[2, 2, 0, 0]} name="a" />
        <Bar dataKey="b" fill={SERIES[1]} radius={[2, 2, 0, 0]} name="b" />
        <Bar dataKey="c" fill={SERIES[2]} radius={[2, 2, 0, 0]} name="c" />
        <Bar dataKey="d" fill={SERIES[3]} radius={[2, 2, 0, 0]} name="d" />
      </BarChart>
    </ResponsiveContainer>
  );
}

function HorzBarChart({ height }: { height: number }) {
  return (
    <ResponsiveContainer width="100%" height={height}>
      <BarChart data={H_BAR_DATA} layout="vertical" margin={{ top: 4, right: 48, left: 0, bottom: 4 }}>
        <CartesianGrid horizontal={false} strokeDasharray="3 3" stroke="#e0e0e0" />
        <XAxis type="number" tickFormatter={fmtY} tick={TICK} axisLine={false} tickLine={false} />
        <YAxis type="category" dataKey="name" tick={TICK} axisLine={false} tickLine={false} width={80} />
        <RechartsTooltip formatter={(v: any) => fmtY(v as number)} contentStyle={TOOLTIP_STYLE} labelStyle={TOOLTIP_LABEL_STYLE} itemStyle={TOOLTIP_ITEM_STYLE} />
        <Bar dataKey="value" fill={PRIMARY} radius={[0, 2, 2, 0]}
          label={{ position: 'right', formatter: (v: any) => (v as number).toLocaleString(), style: { fontSize: 10, fill: '#555', fontFamily: GEIST } }} />
      </BarChart>
    </ResponsiveContainer>
  );
}

// ─── Chart variants ───────────────────────────────────────────────────────────

// How many ticks to show per interval across a 2-year window
const MAX_TICKS: Record<string, number> = { Day: 12, Week: 12, Month: 12, Quarter: 8, Year: 3 };

function sortKeysByParam(keys: SplitSeriesKey[], data: LineRow[], sortBy: string): SplitSeriesKey[] {
  return [...keys].sort((a, b) => {
    const aVals = data.map(r => r[a] as number);
    const bVals = data.map(r => r[b] as number);
    const avg = (arr: number[]) => arr.reduce((s, v) => s + v, 0) / arr.length;
    const sum = (arr: number[]) => arr.reduce((s, v) => s + v, 0);
    switch (sortBy) {
      case 'top-avg':    return avg(bVals) - avg(aVals);
      case 'top-max':    return Math.max(...bVals) - Math.max(...aVals);
      case 'top-total':  return sum(bVals) - sum(aVals);
      case 'bottom-avg': return avg(aVals) - avg(bVals);
      case 'bottom-min': return Math.min(...aVals) - Math.min(...bVals);
      default:           return 0;
    }
  });
}

function MultiLineChart({ height, xAxisInterval = 'Month', splitCount = 1, splitSortBy, chartVariant = 'click-highlight' }: { height: number; xAxisInterval?: string; splitCount?: number; splitSortBy?: string; chartVariant?: ChartVariant }) {
  const data     = LINE_DATA[xAxisInterval] ?? LINE_DATA.Month;
  const baseKeys = splitSortBy
    ? sortKeysByParam([...SPLIT_SERIES_KEYS], data, splitSortBy)
    : [...SPLIT_SERIES_KEYS];
  const allKeys  = baseKeys.slice(0, Math.max(1, splitCount)) as SplitSeriesKey[];
  const colorMap = Object.fromEntries(allKeys.map((k, i) => [k, CHART_COLORS[i]])) as Record<SplitSeriesKey, string>;

  const variant = chartVariant;

  const [highlighted,     setHighlighted]     = useState<Set<SplitSeriesKey>>(new Set());
  const [hoveredKey,      setHoveredKey]      = useState<SplitSeriesKey | null>(null);
  const [showSeriesPanel, setShowSeriesPanel] = useState(false);

  useEffect(() => { setHighlighted(new Set()); setHoveredKey(null); setShowSeriesPanel(false); }, [variant]);

  const maxTicks     = MAX_TICKS[xAxisInterval] ?? 12;
  const tickInterval = data.length <= maxTicks ? 0 : Math.ceil(data.length / maxTicks) - 1;

  const chartH = height;

  // ── Interaction helpers ───────────────────────────────────────────────────
  const hasHighlight  = highlighted.size > 0;
  const toggleHighlight = (key: SplitSeriesKey) =>
    setHighlighted(prev => { const n = new Set(prev); n.has(key) ? n.delete(key) : n.add(key); return n; });

  const lastRow = data[data.length - 1];
  const top5    = new Set([...allKeys].sort((a, b) => (lastRow[b] as number) - (lastRow[a] as number)).slice(0, 5));

  const getOpacity = (key: SplitSeriesKey): number => {
    if (variant === 'hover-isolate')                      return hoveredKey ? (hoveredKey === key ? 1 : 0.08) : 1;
    if (variant === 'click-highlight' || variant === 'selected-only') return hasHighlight ? (highlighted.has(key) ? 1 : 0.1) : 1;
    if (variant === 'always-dim')                         return top5.has(key) ? 1 : 0.12;
    return 1;
  };
  const getWidth = (key: SplitSeriesKey): number =>
    (((variant === 'click-highlight' || variant === 'selected-only') && highlighted.has(key)) || (variant === 'hover-isolate' && hoveredKey === key)) ? 2.5 : 1.5;

  // ── Shared tooltip ────────────────────────────────────────────────────────
  const tooltipContent = ({ active, payload, label }: any) => {
    if (!active || !payload?.length) return null;
    const sorted   = [...payload].sort((a: any, b: any) => (b.value as number) - (a.value as number));
    const hiKeys   = (variant === 'click-highlight' || variant === 'selected-only') && hasHighlight ? [...highlighted]
                   : variant === 'hover-isolate' && hoveredKey ? [hoveredKey] : [];
    const hiSet    = new Set(hiKeys);
    const hasSplit = hiKeys.length > 0;
    const hi  = hasSplit ? sorted.filter((e: any) => hiSet.has(e.dataKey)) : sorted;
    const dim = hasSplit ? sorted.filter((e: any) => !hiSet.has(e.dataKey)) : [];

    const entryRow = (entry: any, strong: boolean) => (
      <Box key={entry.dataKey} sx={{ display: 'flex', alignItems: 'center', gap: 1, py: 0.2 }}>
        <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: entry.color, flexShrink: 0 }} />
        <Typography sx={{ fontSize: 11, fontFamily: GEIST, color: strong ? 'text.primary' : 'text.secondary', flex: 1, fontWeight: strong ? 500 : 400 }}>
          {SERIES_NAMES[entry.dataKey as SplitSeriesKey] ?? entry.dataKey}
        </Typography>
        <Typography sx={{ fontSize: 11, fontFamily: GEIST, fontWeight: strong ? 600 : 400, pl: 2, flexShrink: 0 }}>
          {fmtY(entry.value as number)}
        </Typography>
      </Box>
    );
    return (
      <Box sx={{ ...TOOLTIP_STYLE, bgcolor: 'background.paper', border: '1px solid', borderColor: 'divider', p: 1.5, minWidth: 240, borderRadius: '6px' }}>
        <Typography sx={{ fontSize: 11, fontFamily: GEIST, fontWeight: 600, mb: 0.5 }}>{label}</Typography>
        {hi.map((e: any) => entryRow(e, hasSplit))}
        {dim.length > 0 && (
          <>
            <Box sx={{ borderTop: '1px solid', borderColor: 'divider', my: 0.75, mx: -1.5 }} />
            {dim.map((e: any) => <Box key={e.dataKey} sx={{ opacity: 0.45 }}>{entryRow(e, false)}</Box>)}
          </>
        )}
      </Box>
    );
  };
  const TP = { wrapperStyle: { zIndex: 100, borderRadius: '6px', overflow: 'visible' }, offset: 80, allowEscapeViewBox: { x: true, y: true }, content: tooltipContent };

  // ── Shared interactive legend ─────────────────────────────────────────────
  const interactionLegend = (
    <Legend wrapperStyle={{ zIndex: 10 }} content={({ payload }) => (
      <Box sx={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: 0.5, pt: 0.5 }}>
        {(payload ?? []).map((entry: any) => {
          const key   = (entry.dataKey ?? entry.value) as SplitSeriesKey;
          const isHi  = highlighted.has(key);
          const isDim = hasHighlight && !isHi;
          const isHov = hoveredKey === key;
          const opacity = variant === 'hover-isolate'                         ? (hoveredKey && !isHov ? 0.35 : 1)
                        : (variant === 'click-highlight' || variant === 'selected-only') ? (isDim ? 0.35 : 1)
                        : variant === 'always-dim'                          ? (top5.has(key) ? 1 : 0.35) : 1;
          return (
            <Box key={key}
              onClick={() => variant === 'click-highlight' && toggleHighlight(key)}
              onMouseEnter={() => variant === 'hover-isolate' && setHoveredKey(key)}
              onMouseLeave={() => variant === 'hover-isolate' && setHoveredKey(null)}
              sx={{
                display: 'flex', alignItems: 'center', gap: 0.5,
                px: 0.75, py: 0.2, borderRadius: 1, opacity, transition: 'all 0.15s',
                cursor: variant === 'click-highlight' ? 'pointer' : 'default',
                bgcolor: isHi ? 'action.selected' : isHov ? 'action.hover' : 'transparent',
                border: '1px solid', borderColor: isHi ? 'primary.main' : 'transparent',
                '&:hover': variant === 'click-highlight' ? { bgcolor: 'action.hover' } : {},
              }}
            >
              <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: colorMap[key], flexShrink: 0 }} />
              <span style={{ fontSize: 11, fontFamily: GEIST, color: '#333' }}>{SERIES_NAMES[key]}</span>
            </Box>
          );
        })}
        {hasHighlight && variant === 'click-highlight' && (
          <Box onClick={() => setHighlighted(new Set())} sx={{ px: 0.75, py: 0.2, cursor: 'pointer', opacity: 0.6, '&:hover': { opacity: 1 } }}>
            <span style={{ fontSize: 11, fontFamily: GEIST, color: '#888' }}>Clear</span>
          </Box>
        )}
      </Box>
    )} />
  );

  // ── Common lines ──────────────────────────────────────────────────────────
  const commonLines = allKeys.map(key => (
    <Line key={key} type="linear" dataKey={key} stroke={colorMap[key]} dot={false}
      strokeWidth={getWidth(key)} strokeOpacity={getOpacity(key)} name={key} />
  ));

  // ── 1. Base chart — interaction variants & log scale ──────────────────────
  const logData = data.map(row => {
    const nr = { ...row } as any;
    allKeys.forEach(k => { if ((nr[k] as number) <= 0) nr[k] = 0.1; });
    return nr;
  });

  const baseChart = (h: number, useLog = false) => (
    <ResponsiveContainer width="100%" height={h} style={{ overflow: 'visible' }}>
      <LineChart data={useLog ? logData : data} margin={{ top: 8, right: 8, left: 0, bottom: 0 }} style={{ overflow: 'visible' }}>
        <CartesianGrid {...GRID} />
        <XAxis dataKey="date" tick={TICK} axisLine={false} tickLine={false} interval={tickInterval} />
        <YAxis tickFormatter={v => fmtY(useLog && v < 1 ? 0 : v)} tick={TICK} axisLine={false} tickLine={false} width={36}
          scale={useLog ? 'log' : 'auto'} domain={useLog ? ['auto', 'auto'] : undefined} allowDataOverflow={useLog} />
        <RechartsTooltip {...TP} />
        {allKeys.length > 1 && interactionLegend}
        {commonLines}
      </LineChart>
    </ResponsiveContainer>
  );

  // ── 2. Small multiples ────────────────────────────────────────────────────
  const smallMultiples = (h: number) => (
    <Box sx={{
      height: h, overflowY: 'auto', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 0.5,
      '&::-webkit-scrollbar': { width: 3 }, '&::-webkit-scrollbar-thumb': { bgcolor: 'divider', borderRadius: 2 },
    }}>
      {allKeys.map(key => (
        <Box key={key}>
          <Typography sx={{ fontSize: 9, color: colorMap[key], fontFamily: GEIST, fontWeight: 600, lineHeight: 1.3, mb: 0.25, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
            {SERIES_NAMES[key]}
          </Typography>
          <ResponsiveContainer width="100%" height={58}>
            <LineChart data={data} margin={{ top: 2, right: 4, left: 0, bottom: 0 }}>
              <XAxis dataKey="date" tick={{ fontSize: 7, fill: '#bbb', fontFamily: GEIST }} axisLine={false} tickLine={false} interval={Math.ceil(tickInterval * 2)} />
              <YAxis tickFormatter={fmtY} tick={{ fontSize: 7, fill: '#bbb', fontFamily: GEIST }} axisLine={false} tickLine={false} width={22} />
              <RechartsTooltip wrapperStyle={{ zIndex: 100 }} contentStyle={{ fontSize: 10, fontFamily: GEIST, borderRadius: 4, padding: '2px 6px' }} formatter={(v: any) => fmtY(v)} />
              <Line type="linear" dataKey={key} stroke={colorMap[key]} dot={false} strokeWidth={1.5} />
            </LineChart>
          </ResponsiveContainer>
        </Box>
      ))}
    </Box>
  );

  // ── 3. Focus + context (brush zoom) ──────────────────────────────────────
  const focusContext = (h: number) => (
    <ResponsiveContainer width="100%" height={h} style={{ overflow: 'visible' }}>
      <LineChart data={data} margin={{ top: 8, right: 8, left: 0, bottom: 4 }} style={{ overflow: 'visible' }}>
        <CartesianGrid {...GRID} />
        <XAxis dataKey="date" tick={TICK} axisLine={false} tickLine={false} interval={tickInterval} />
        <YAxis tickFormatter={fmtY} tick={TICK} axisLine={false} tickLine={false} width={36} />
        <RechartsTooltip {...TP} />
        {allKeys.length > 1 && interactionLegend}
        {commonLines}
        <Brush dataKey="date" height={26} stroke="#e0e0e0" fill="#f8f8f8" travellerWidth={5} tickFormatter={() => ''}>
          <LineChart>
            {allKeys.map(key => <Line key={key} type="linear" dataKey={key} stroke={colorMap[key]} dot={false} strokeWidth={0.75} strokeOpacity={0.5} />)}
          </LineChart>
        </Brush>
      </LineChart>
    </ResponsiveContainer>
  );

  // ── 4. Normalized 100% stacked area ───────────────────────────────────────
  const normalizedData = data.map(row => {
    const total = allKeys.reduce((s, k) => s + (row[k] as number), 0);
    const nr: Record<string, number | string> = { date: row.date };
    allKeys.forEach(k => { nr[k] = total > 0 ? Math.round((row[k] as number) / total * 1000) / 10 : 0; });
    return nr;
  });

  const normalized = (h: number) => (
    <ResponsiveContainer width="100%" height={h} style={{ overflow: 'visible' }}>
      <AreaChart data={normalizedData} margin={{ top: 8, right: 8, left: 0, bottom: 0 }} style={{ overflow: 'visible' }}>
        <CartesianGrid {...GRID} />
        <XAxis dataKey="date" tick={TICK} axisLine={false} tickLine={false} interval={tickInterval} />
        <YAxis tickFormatter={v => `${v}%`} tick={TICK} axisLine={false} tickLine={false} width={36} domain={[0, 100]} />
        <RechartsTooltip
          wrapperStyle={{ zIndex: 100, borderRadius: '6px', overflow: 'visible' }} offset={24}
          content={({ active, payload, label }: any) => {
            if (!active || !payload?.length) return null;
            const sorted = [...payload].sort((a: any, b: any) => (b.value as number) - (a.value as number));
            return (
              <Box sx={{ ...TOOLTIP_STYLE, bgcolor: 'background.paper', border: '1px solid', borderColor: 'divider', p: 1.5, minWidth: 220, borderRadius: '6px' }}>
                <Typography sx={{ fontSize: 11, fontFamily: GEIST, fontWeight: 600, mb: 0.5 }}>{label}</Typography>
                {sorted.map((e: any) => (
                  <Box key={e.dataKey} sx={{ display: 'flex', alignItems: 'center', gap: 1, py: 0.2 }}>
                    <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: e.fill, flexShrink: 0 }} />
                    <Typography sx={{ fontSize: 11, fontFamily: GEIST, color: 'text.secondary', flex: 1 }}>{SERIES_NAMES[e.dataKey as SplitSeriesKey] ?? e.dataKey}</Typography>
                    <Typography sx={{ fontSize: 11, fontFamily: GEIST, fontWeight: 500, pl: 2, flexShrink: 0 }}>{e.value}%</Typography>
                  </Box>
                ))}
              </Box>
            );
          }}
        />
        {allKeys.length > 1 && (
          <Legend wrapperStyle={{ zIndex: 10, fontSize: 11, fontFamily: GEIST }}
            formatter={v => <span style={{ color: '#333', fontFamily: GEIST }}>{SERIES_NAMES[v as SplitSeriesKey] ?? v}</span>} />
        )}
        {allKeys.map(key => (
          <Area key={key} type="linear" dataKey={key} stackId="1" stroke={colorMap[key]} fill={colorMap[key]} fillOpacity={0.75} dot={false} name={key} />
        ))}
      </AreaChart>
    </ResponsiveContainer>
  );

  // ── 5. Inline labels at right edge ───────────────────────────────────────
  const inlineLabels = (h: number) => (
    <ResponsiveContainer width="100%" height={h} style={{ overflow: 'visible' }}>
      <LineChart data={data} margin={{ top: 8, right: 136, left: 0, bottom: 0 }} style={{ overflow: 'visible' }}>
        <CartesianGrid {...GRID} />
        <XAxis dataKey="date" tick={TICK} axisLine={false} tickLine={false} interval={tickInterval} />
        <YAxis tickFormatter={fmtY} tick={TICK} axisLine={false} tickLine={false} width={36} />
        <RechartsTooltip {...TP} />
        {allKeys.map(key => (
          <Line key={key} type="linear" dataKey={key} stroke={colorMap[key]} strokeWidth={1.5}
            strokeOpacity={getOpacity(key)} name={key}
            dot={(props: any) => {
              if (props.index !== data.length - 1) return <g key={props.index} />;
              const name  = SERIES_NAMES[key];
              const short = name.length > 20 ? name.slice(0, 19) + '…' : name;
              return (
                <g key={`il-${key}`}>
                  <circle cx={props.cx} cy={props.cy} r={2.5} fill={colorMap[key]} />
                  <text x={props.cx + 6} y={props.cy} dy={4} fontSize={9} fill={colorMap[key]} fontFamily={GEIST} textAnchor="start">{short}</text>
                </g>
              );
            }}
          />
        ))}
      </LineChart>
    </ResponsiveContainer>
  );

  // ── 6. Floating labels at each series' peak ───────────────────────────────
  const peakMap = Object.fromEntries(allKeys.map(key => {
    let maxIdx = 0; let maxVal = -Infinity;
    data.forEach((row, i) => { const v = row[key] as number; if (v > maxVal) { maxVal = v; maxIdx = i; } });
    return [key, maxIdx];
  }));

  const floatingLabels = (h: number) => (
    <ResponsiveContainer width="100%" height={h} style={{ overflow: 'visible' }}>
      <LineChart data={data} margin={{ top: 20, right: 8, left: 0, bottom: 0 }} style={{ overflow: 'visible' }}>
        <CartesianGrid {...GRID} />
        <XAxis dataKey="date" tick={TICK} axisLine={false} tickLine={false} interval={tickInterval} />
        <YAxis tickFormatter={fmtY} tick={TICK} axisLine={false} tickLine={false} width={36} />
        <RechartsTooltip {...TP} />
        {allKeys.map(key => {
          const peak = peakMap[key];
          return (
            <Line key={key} type="linear" dataKey={key} stroke={colorMap[key]} strokeWidth={1.5}
              strokeOpacity={getOpacity(key)} name={key}
              dot={(props: any) => {
                if (props.index !== peak) return <g key={props.index} />;
                const name  = SERIES_NAMES[key];
                const short = name.length > 16 ? name.slice(0, 15) + '…' : name;
                return (
                  <g key={`fl-${key}`}>
                    <circle cx={props.cx} cy={props.cy} r={3} fill={colorMap[key]} />
                    <text x={props.cx} y={props.cy - 8} fontSize={9} fill={colorMap[key]} fontFamily={GEIST} textAnchor="middle">{short}</text>
                  </g>
                );
              }}
            />
          );
        })}
      </LineChart>
    </ResponsiveContainer>
  );

  // ── 7. Selected-only: trigger button + MUI Menu + selected chips ─────────────
  const seriesTriggerRef = useRef<HTMLDivElement>(null);
  const LEGEND_H = 46;

  const selectedOnlyChart = (h: number) => (
    <Box sx={{ height: h, display: 'flex', flexDirection: 'column', overflow: 'visible' }}>
      <ResponsiveContainer width="100%" height={h - LEGEND_H} style={{ overflow: 'visible' }}>
        <LineChart data={data} margin={{ top: 8, right: 8, left: 0, bottom: 0 }} style={{ overflow: 'visible' }}>
          <CartesianGrid {...GRID} />
          <XAxis dataKey="date" tick={TICK} axisLine={false} tickLine={false} interval={tickInterval} />
          <YAxis tickFormatter={fmtY} tick={TICK} axisLine={false} tickLine={false} width={36} />
          <RechartsTooltip {...TP} />
          {allKeys.map(key => (
            <Line key={key} type="monotone" dataKey={key} stroke={colorMap[key]} dot={false}
              strokeWidth={getWidth(key)} strokeOpacity={getOpacity(key)} name={key} />
          ))}
        </LineChart>
      </ResponsiveContainer>

      {/* Legend row */}
      <Box sx={{ height: LEGEND_H, display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 0.5, pt: 0.75 }}>

        {/* Trigger — always first */}
        <Box
          ref={seriesTriggerRef}
          onClick={() => setShowSeriesPanel(v => !v)}
          sx={{
            display: 'inline-flex', alignItems: 'center', gap: 0.25,
            px: 0.75, py: 0.3, borderRadius: 1, cursor: 'pointer', userSelect: 'none',
            border: '1px solid',
            borderColor: showSeriesPanel ? 'primary.main' : 'divider',
            bgcolor: showSeriesPanel ? 'rgba(43,122,140,0.06)' : 'transparent',
            fontSize: 11, fontFamily: GEIST,
            color: showSeriesPanel ? 'primary.main' : 'text.secondary',
            '&:hover': { borderColor: 'primary.light' },
          }}
        >
          Series
          {showSeriesPanel
            ? <KeyboardArrowUpIcon sx={{ fontSize: 14 }} />
            : <KeyboardArrowDownIcon sx={{ fontSize: 14 }} />
          }
        </Box>

        {/* MUI Menu anchored to the trigger */}
        <Menu
          anchorEl={seriesTriggerRef.current}
          open={showSeriesPanel}
          onClose={() => setShowSeriesPanel(false)}
          anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
          transformOrigin={{ vertical: 'bottom', horizontal: 'left' }}
          disableAutoFocusItem
          PaperProps={{
            sx: {
              minWidth: 220, maxHeight: 260, borderRadius: '8px',
              border: '1px solid rgba(33,33,33,0.10)',
              boxShadow: '0 8px 8px -4px rgba(0,0,0,0.04), 0 20px 24px -4px rgba(0,0,0,0.08)',
            },
          }}
        >
          {allKeys.map(key => {
            const isSelected = highlighted.has(key);
            return (
              <MenuItem
                key={key}
                onClick={() => toggleHighlight(key)}
                sx={{ py: 0.75, minHeight: 0, gap: 1 }}
              >
                <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: colorMap[key], flexShrink: 0 }} />
                <ListItemText primaryTypographyProps={{ sx: { fontSize: 13, fontFamily: GEIST } }}>
                  {SERIES_NAMES[key]}
                </ListItemText>
                {isSelected && (
                  <ListItemIcon sx={{ minWidth: 0, ml: 1 }}>
                    <CheckIcon sx={{ fontSize: 14, color: 'primary.main' }} />
                  </ListItemIcon>
                )}
              </MenuItem>
            );
          })}
        </Menu>

        {/* Selected chips */}
        {[...highlighted].map(key => (
          <Box key={key} sx={{
            display: 'inline-flex', alignItems: 'center', gap: 0.5,
            px: 0.75, py: 0.3, borderRadius: 1,
            border: '1px solid', borderColor: 'primary.main',
            bgcolor: 'rgba(43,122,140,0.06)',
          }}>
            <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: colorMap[key], flexShrink: 0 }} />
            <span style={{ fontSize: 11, fontFamily: GEIST, color: '#333' }}>{SERIES_NAMES[key]}</span>
            <Box
              onClick={() => toggleHighlight(key)}
              sx={{ ml: 0.25, cursor: 'pointer', lineHeight: 1, display: 'flex', alignItems: 'center', color: 'text.disabled', '&:hover': { color: 'text.primary' } }}
            >
              <span style={{ fontSize: 14, lineHeight: 1 }}>×</span>
            </Box>
          </Box>
        ))}

        {highlighted.size > 0 && (
          <Box onClick={() => setHighlighted(new Set())} sx={{ px: 0.5, cursor: 'pointer', opacity: 0.5, '&:hover': { opacity: 1 } }}>
            <span style={{ fontSize: 11, fontFamily: GEIST, color: '#888' }}>Clear</span>
          </Box>
        )}
      </Box>
    </Box>
  );

  // ── Render ────────────────────────────────────────────────────────────────
  const renderChart = () => {
    switch (variant) {
      case 'click-highlight':
      case 'hover-isolate':
      case 'always-dim':      return baseChart(chartH);
      case 'selected-only':   return selectedOnlyChart(chartH);
      case 'small-multiples': return smallMultiples(chartH);
      case 'focus-context':   return focusContext(chartH);
      case 'log-scale':       return baseChart(chartH, true);
      case 'normalized':      return normalized(chartH);
      case 'inline-labels':   return inlineLabels(chartH);
      case 'floating-labels': return floatingLabels(chartH);
    }
  };

  return (
    <Box sx={{ height, overflow: 'visible' }}>
      {renderChart()}
    </Box>
  );
}

function PercentTile({ height }: { height: number }) {
  const pct = 31.2;
  const donut = [
    { value: pct, color: PRIMARY },
    { value: 100 - pct, color: '#E8E8E8' },
  ];
  const size = Math.min(height - 20, 200);
  return (
    <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height }}>
      <Box sx={{ position: 'relative', width: size, height: size }}>
        <PieChart width={size} height={size}>
          <Pie data={donut} cx={size / 2 - 5} cy={size / 2 - 5}
            innerRadius={size * 0.33} outerRadius={size * 0.46}
            startAngle={90} endAngle={-270} dataKey="value" strokeWidth={0}>
            {donut.map((entry, i) => <Cell key={i} fill={entry.color} />)}
          </Pie>
        </PieChart>
        <Box sx={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', textAlign: 'center', pointerEvents: 'none' }}>
          <Typography sx={{ fontSize: size * 0.13, fontWeight: 700, lineHeight: 1.1, fontFamily: GEIST }}>31.2%</Typography>
          <Typography variant="caption" color="text.secondary" sx={{ fontFamily: GEIST }}>3128/10,057</Typography>
        </Box>
      </Box>
    </Box>
  );
}

function PieChartTile({ height }: { height: number }) {
  return (
    <Box sx={{ height }}>
      <ResponsiveContainer width="100%" height="100%">
        <PieChart>
          <Pie data={PIE_DATA} cx="50%" cy="50%" outerRadius={Math.min(height * 0.38, 90)}
            dataKey="value" strokeWidth={1} stroke="#fff">
            {PIE_DATA.map((entry, i) => <Cell key={i} fill={entry.color} />)}
          </Pie>
          <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: 11, fontFamily: GEIST }} formatter={() => 'Label'} />
          <RechartsTooltip contentStyle={TOOLTIP_STYLE} labelStyle={TOOLTIP_LABEL_STYLE} itemStyle={TOOLTIP_ITEM_STYLE} />
        </PieChart>
      </ResponsiveContainer>
    </Box>
  );
}

// ─── TileContent ──────────────────────────────────────────────────────────────

export function TileContent({ type, height = 280, xAxisInterval, splitCount, splitSortBy, chartVariant }: { type: TileType; height?: number; xAxisInterval?: string; splitCount?: number; splitSortBy?: string; chartVariant?: ChartVariant }) {
  switch (type) {
    case 'verticalBar':   return <VertBarChart height={height} />;
    case 'multiBar':      return <MultiBarChart height={height} />;
    case 'horizontalBar': return <HorzBarChart height={height} />;
    case 'line':          return <MultiLineChart height={height} xAxisInterval={xAxisInterval} splitCount={splitCount} splitSortBy={splitSortBy} chartVariant={chartVariant} />;
    case 'percent':       return <PercentTile height={height} />;
    case 'pie':           return <PieChartTile height={height} />;
  }
}

// ─── Initial tiles ────────────────────────────────────────────────────────────

export const INITIAL_TILES: Tile[] = [
  { id: 1, name: 'Tile Name', type: 'verticalBar' },
  { id: 2, name: 'Tile Name', type: 'multiBar' },
  { id: 3, name: 'Tile Name', type: 'percent' },
  { id: 4, name: 'Tile Name', type: 'line' },
  { id: 5, name: 'Tile Name', type: 'pie' },
  { id: 6, name: 'Tile Name', type: 'horizontalBar' },
];
